### ISSUE TITLE
TintTypedArray的getDrawableIfKnown会报错

### ISSUE THREAD

**Issue by changety** [shwenzhang/AndResGuard#101]
Caused by: android.content.res.Resources$NotFoundException: File r/v/a8q.jpg from drawable resource ID #0x7f02053e
at android.content.res.Resources.loadDrawable(Resources.java:2052)
at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:317)
at android.content.res.Resources.getDrawable(Resources.java:696)
at android.support.v4.content.ContextCompat.getDrawable(ProGuard:346)
at android.support.v7.widget.AppCompatDrawableManager.getDrawable(ProGuard:197)
at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(ProGuard:77)
at android.support.v7.app.AppCompatDelegateImplBase.(ProGuard:127)
at android.support.v7.app.AppCompatDelegateImplV9.(ProGuard:147)
at android.support.v7.app.AppCompatDelegateImplV11.(ProGuard:27)
at android.support.v7.app.AppCompatDelegateImplV14.(ProGuard:50)
at android.support.v7.app.AppCompatDelegate.create(ProGuard:201)
at android.support.v7.app.AppCompatDelegate.create(ProGuard:181)
at android.support.v7.app.AppCompatActivity.getDelegate(ProGuard:521)
at android.support.v7.app.AppCompatActivity.onCreate(ProGuard:71)

**Comment by changety** [comment]
我们在项目中设置过该activity的windowBackground

**Comment by simpleton** [comment]
麻烦确认一下这个错误是否只在miui上出现，这个callstack暂时还看不出是什么问题。 r/v/a8q.jpg 是一个什么资源文件呢？

**Comment by changety** [comment]
r/v/a8q.jpg  就是  <item name="android:windowBackground">@drawable/a8q</item><br> 里面的用到drawable

**Comment by simpleton** [comment]
是app本身带有的drawable么？因为miui有一些换肤的功能是通过全路径替换资源的，这些资源是需要加入白名单的。

**Comment by changety** [comment]
我也怀疑是这个原因，也有可能是用户自行修改了这张图。 暂且把这张图加入白名单

**Comment by simpleton** [comment]
@changety 关于此issue还有更多的线索么？

**Comment by simpleton** [comment]
暂时关闭了，如果有新的问题请再重新打开。
