### ISSUE TITLE
能否支持下指定buildType？

### ISSUE THREAD

**Issue by hacket** [shwenzhang/AndResGuard#106]
看了下有个相关的issue关闭了。但现在我们这边会定义多个`buildType`，其中会有`releaseLog`，**支持log输出，proguard和resguard**，基本上和release包没区别，只是打开了log输出功能，用于方便跟踪crash，然后给qa测试。resguard目前只支持release吧，能否支持下指定buildType？

**Comment by simpleton** [comment]
能否提供一下这个buildType得代码片段，我好在example里模拟一个相同的buildType

2016-10-27 15:31 GMT+08:00 Shengjie Sun <sunsj1231@gmail.com>:

> 嗯，可以支持，周末我实现下吧。以前的issue我印象是支持多个Flavor。
>

**Comment by simpleton** [comment]
嗯，可以支持，周末我实现下吧。以前的issue我印象是支持多个Flavor。

**Comment by hacket** [comment]
```groovy
buildTypes {
	release {
		// 不显示Log, 在java代码中的调用方式为：
		buildConfigField "boolean", "DEBUG_MODE", "false"
		buildConfigField "boolean", "LOG_DEBUG", "false"
		debuggable false
		minifyEnabled true
		zipAlignEnabled true
		shrinkResources true
		proguardFiles getDefaultProguardFile('proguard-android.txt'), "$rootDir/config/proguard-rules.pro"
		signingConfig signingConfigs.release
	}
	releaseLog {
		buildConfigField "boolean", "DEBUG_MODE", "false"
		buildConfigField "boolean", "LOG_DEBUG", "true"
		debuggable true
		minifyEnabled true
		zipAlignEnabled true
		shrinkResources true
		proguardFiles getDefaultProguardFile('proguard-android.txt'), "$rootDir/config/proguard-rules.pro"
		signingConfig signingConfigs.release
	}
	debug {
		buildConfigField "boolean", "DEBUG_MODE", "true"
		buildConfigField "boolean", "LOG_DEBUG", "true"
		debuggable true
		shrinkResources false
		zipAlignEnabled true
		minifyEnabled false
		// proguardFiles getDefaultProguardFile('proguard-android.txt'), "$rootDir/config/proguard-rules.pro"
		signingConfig signingConfigs.debug
	}
}
```

**Comment by simpleton** [comment]
@hacket 可以升级到1.1.14尝试下。

**Comment by hacket** [comment]
ok,thx!

**Comment by hacket** [comment]
目前的配置是：
```java
android {
	buildTypes {
		release {
			// ...
		}
		releaseLog {
			// ...
		}
		debug {
			// ...
		}
	}
	productFlavors {
		dev {
		}
		yingyongbao {
		}
	}
}
```
更新到`1.1.14`后，出现几个task
![image](https://cloud.githubusercontent.com/assets/5653588/19844689/44a3e1da-9f6a-11e6-9dfe-8ac63b18dbcb.png)
现在我执行`gradle resguardDebug`，这个应该是把所有`debug*productFlavors`的包给resguard，但现在错误了：
![image](https://cloud.githubusercontent.com/assets/5653588/19844769/1f98e056-9f6b-11e6-8605-ddc60f185813.png)
请问下什么问题呢？

还有个问题：
这种task为何不是类似`resguardDevDebug`命名，而是`resguardDebug`，我只想对一个buildType中的某个flavor中resguard怎么实现呢，为何不是通过`resguard[Flavors][BuildTypes]`来命名的呢？

@simpleton

**Comment by simpleton** [comment]
这里参考了assemble的命名规则，你说的方法也是可以实现的。另外你说的问题我跟进下

**Comment by simpleton** [comment]
可否提供一下call stack呢？

**Comment by hacket** [comment]
```java
:app:resguardReleaseLog
resourceprpguard begin

FAILURE: Build failed with an exception.

* What went wrong:
Could not dispatch a message to the daemon.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.launcher.daemon.client.DaemonConnectionException: Could not dispatch
a message to the daemon.
        at org.gradle.launcher.daemon.client.DaemonClientConnection.dispatch(Dae
monClientConnection.java:68)
        at org.gradle.launcher.daemon.client.DaemonClientConnection.dispatch(Dae
monClientConnection.java:35)
        at org.gradle.launcher.daemon.client.DaemonClientInputForwarder$ForwardT
extStreamToConnection.endOfStream(DaemonClientInputForwarder.java:78)
        at org.gradle.launcher.daemon.client.InputForwarder$1.run(InputForwarder
.java:95)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.
onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableE
xecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.internal.remote.internal.MessageIOException: Could not wri
te '/127.0.0.1:60366'.
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(Socke
tConnection.java:121)
        at org.gradle.launcher.daemon.client.DaemonClientConnection.dispatch(Dae
monClientConnection.java:59)
        ... 8 more
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
        at sun.nio.ch.SocketDispatcher.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutpu
tStream.writeWithNonBlockingRetry(SocketConnection.java:259)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutpu
tStream.writeBufferToChannel(SocketConnection.java:247)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutpu
tStream.flush(SocketConnection.java:241)
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(Socke
tConnection.java:119)
        ... 9 more
```

**Comment by simpleton** [comment]
@hacket sorry for late feedback, could you try with `gradle --stop && gradle clean resguardDebug`？

**Comment by hacket** [comment]
还是和上面一样的错误。

**Comment by bkzb** [comment]
打包成功了。。然后一启动说Tinker Exception:onCreate method not found。。

**Comment by simpleton** [comment]
@bkzb 这个是Tinker相关的错误，应该和`AndResGuard`无关。

**Comment by simpleton** [comment]
@hacket 前一阵在休假，没有持续跟进，你的问题还存在么？从你提供的log看不出来更多的细节。

**Comment by imknown** [comment]
@simpleton Hi, 我想请教一个问题:
我想改进一下 `buildTypes` 和 `productFlavors` 的 createTask 方法, 
然后 pull request, 但是 构建 `AndResGuard-gradle-plugin` 之后, 
如何 在 `AndResGuard-example` 中 进行调试额? 看了 Gralde plugins 官方教程, 
已写 `classpath group: 'com.tencent.mm', name: 'AndResGuard-gradle-plugin', version: '1.1.14'`.

**Comment by simpleton** [comment]
@imknown 首先回答你的问题，因为我没有把gradle plugin和example写在一个工程里，所以需要你发布到本地，需要运行`publishToMavenLocal`的task，然后在example引用。另外由于gradle默认有cache，所以你需要引用的时候打开`changing`这个开关。比如
```
classpath ('com.tencent.mm:AndResGuard-gradle-plugin:1.1.14') { changing=true }
```

PS：现在createTask有什么问题么？

**Comment by imknown** [comment]
@simpleton 谢谢解答, 跪谢中~ 第一次做 gradle plugin~

我看了源码, 只是 分别遍历 `buildTypes` 和 `productFlavors` 创建 tasks, 
但是 因为我这里 `buildTypes` 和 `productFlavors` 都很多, 
所以 每次 用 `resguardCertainBuildType` 或者 `resguardCertainProductFlavor` task 打包, 
都会打 好几个不需要的 包.

我把 `AndResGuardPlugin.groovy` 改成了 如下代码, 不知道行不行, 
我还没办法验证 😿 

``` groovy
package com.tencent.gradle

import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * Registers the plugin's tasks.
 *
 * @author sim sun (sunsj1231@gmail.com)
 */

class AndResGuardPlugin implements Plugin<Project> {

    @Override
    public void apply(Project project) {
        project.apply plugin: 'osdetector'
        project.extensions.create('andResGuard', AndResGuardExtension)
        project.extensions.add("sevenzip", new ExecutorExtension("sevenzip"))

        project.afterEvaluate {
            project.extensions.android.productFlavors.all { flavor ->
                createTask(project, flavor)
            }

            project.extensions.android.buildTypes.all { buildType ->
                createTask(project, buildType)
            }

            project.extensions.android.productFlavors.all { flavor ->
                project.extensions.android.buildTypes.all { buildType ->
                    def typeName = [flavor, buildType]
                    createTask(project, typeName)
                }
            }

            def ExecutorExtension sevenzip = project.extensions.findByName("sevenzip")
            sevenzip.loadArtifact(project)
        }
    }

    private static def getPascalCaseName(variant) {
        def finalName = new StringBuffer()

        variant.each { name ->
            finalName.append(Character.toUpperCase(variant.name.charAt(0)))
                    .append(variant.name[1..-1])
        }

        finalName.toString()
    }

    private static void createTask(Project project, typeName) {
	    typeName = getPascalCaseName(typeName)
	
        def task = project.task("resguard${typeName}", type: AndResGuardTask)
        task.dependsOn "assemble${typeName}"
    }
}
```

**Comment by simpleton** [comment]
我当时也有由于要不要做成组合的都分开，后来看assemble也是只有一个维度。不过感觉大家的需求貌似是要按组合来的，楼上也有位同学比较倾向于这个。如果你已经写好了，就直接提PR吧。

**Comment by imknown** [comment]
@simpleton haha, 谢谢你提供的思路~~
用两个 project 运行 plugin 和 example, 已经成功完成调试了.
正在 pr ~
