### ISSUE TITLE
如果项目中使用retrollamda，运行resguard任务的时候会报错

### ISSUE THREAD

**Issue by heweimxcz** [shwenzhang/AndResGuard#111]
java.lang.UnsupportedOperationException: Unknown ASTNode child: LambdaExpression
        at lombok.ast.ecj.EcjTreeVisitor.visitOther(EcjTreeVisitor.java:368)
        at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:364)
        at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
        at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:236)
        at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:282)
        at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:252)

**Comment by simpleton** [comment]
https://github.com/evant/gradle-retrolambda/issues/96
这个和resguard无关，是retrolambda会造成lint报错而已，可以忽略的。
