### ISSUE TITLE
com.tencent.mm.androlib.AndrolibException: Could not decode arsc file

### ISSUE THREAD

**Issue by MrPharrell** [shwenzhang/AndResGuard#114]
writing new resources.arsc 
resources.arsc Character Encoding: utf-8
com.tencent.mm.androlib.AndrolibException: Could not decode arsc file
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.write(ARSCDecoder.java:119)
        at com.tencent.mm.androlib.ApkDecoder.decode(ApkDecoder.java:196)
        at com.tencent.mm.resourceproguard.Main.decodeResource(Main.java:86)
        at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:70)
        at com.tencent.mm.resourceproguard.cli.CliMain.run(CliMain.java:193)
        at com.tencent.mm.resourceproguard.cli.CliMain.main(CliMain.java:37)
Caused by: java.io.EOFException
        at java.io.DataInputStream.readFully(DataInputStream.java:197)
        at com.mindprod.ledatastream.LEDataInputStream.readFully(LEDataInputStream.java:179)
        at com.tencent.mm.util.DataInputDelegate.readFully(DataInputDelegate.java:68)
        at com.tencent.mm.util.ExtDataOutput.writeBytes(ExtDataOutput.java:23)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.reWriteTable(ARSCDecoder.java:252)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.writeTable(ARSCDecoder.java:218)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.write(ARSCDecoder.java:116)
        ... 5 more

我也遇到了这个问题，尝试用apktool-v2.2.1和AndroidKiller_v1.3.1查看资源都可以。

**Comment by simpleton** [comment]
@MrPharrell 多谢反馈，可否把apk文件发到我的邮箱呢？sunsj1231[at]gmail.com

**Comment by MrPharrell** [comment]
@shwenzhang 已发，请查收

**Comment by simpleton** [comment]
@MrPharrell sorry for late feedback, please try 1.1.15 version for fixing this issue.

**Comment by shenbuqingyun** [comment]
试试更新到最新的包 classpath 'com.tencent.mm:AndResGuard-gradle-plugin:1.2.17'
