### ISSUE TITLE
混淆时出现异常

### ISSUE THREAD

**Issue by ztc1997** [shwenzhang/AndResGuard#12]
混淆一个很小的apk，是xposed模块，没有activity，发生错误如下

special configFile file path: D:\AndResGuard\config.xml
special output directory path: D:\AndResGuard\outapk
resourceprpguard begin
reading config file, D:\AndResGuard\config.xml
mKeepRoot false
unziping apk to D:\AndResGuard\outapk\temp
decoding resources.arsc
parse to get the exist names in the resouces.arsc first
reading packagename ztc1997.xperiachinesecharclock
Exception in thread "main" java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at java.util.ArrayList.removeAll(ArrayList.java:689)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder$ProguardStringBuilder
.removeStrings(ARSCDecoder.java:1145)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.
java:415)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecod
er.java:323)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder
.java:189)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.ja
va:53)
        at com.tencent.mm.androlib.ApkDecoder.decode(ApkDecoder.java:178)
        at com.tencent.mm.resourceproguard.Main.run(Main.java:303)
        at com.tencent.mm.resourceproguard.Main.main(Main.java:67)

**Comment by shwenzhang** [comment]
能把安装包发到shaowenzhang1986@gmail.com吗？

**Comment by shwenzhang** [comment]
fixed nullpointer
