### ISSUE TITLE
在white list增加packagename.R.id.* 遇到问题

### ISSUE THREAD

**Issue by fannylan** [shwenzhang/AndResGuard#129]
项目需要，必须保证layout中的view id不被混淆，因此在白名单重增加 "packagename.R.id.*", 结果打包时遇到

com.tencent.mm.android.AndrolibException:writeSpecNameStringBlock length is different name 12, tempByte14
at com.tencent.mm.androlib.res.decoder.StringBlock.writeSpecNameStringBlock(StringBlock.java:134)

版本是1.1.10

去掉"packagename.R.id.*"就能正常打包，怎么回事呢，要如何配置才能让id不被混淆呢

**Comment by simpleton** [comment]
@fannylan 请先升级到最新版本尝试下。

**Comment by fannylan** [comment]
升级到1.1.16 也还是会报错

**Comment by fannylan** [comment]
writing new resources.arsc
resources.arsc Character Encoding: utf-8
com.tencent.mm.androlib.AndrolibException: writeSpecNameStringBlock lenght is different  name 12, tempByte 14

        at com.tencent.mm.androlib.res.decoder.StringBlock.writeSpecNameStringBlock(StringBlock.java:151)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.writePackage(ARSCDecoder.java:318)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.writeTable(ARSCDecoder.java:224)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.write(ARSCDecoder.java:127)
        at com.tencent.mm.androlib.ApkDecoder.decode(ApkDecoder.java:196)
        at com.tencent.mm.resourceproguard.Main.decodeResource(Main.java:86)
        at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:70)
        at com.tencent.mm.resourceproguard.Main.run(Main.java:43)
        at com.tencent.mm.resourceproguard.Main.gradleRun(Main.java:37)
        at com.tencent.mm.resourceproguard.Main$gradleRun.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at com.tencent.gradle.AndResGuardTask$_run_closure3.doCall(AndResGuardTask.groovy:106)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:430)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
        at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at com.tencent.gradle.AndResGuardTask.run(AndResGuardTask.groovy:71)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by simpleton** [comment]
@fannylan sorry for late feedback.
我在sample中测试了下，并没有发现你描述的问题。PS:现在的白名单应该会自动增加packagename，不需要手动添加了

**Comment by simpleton** [comment]
@fannylan 
我暂时关闭这个issue了，如果按sample中的方法改造不能work，请重新打开。

**Comment by simpleton** [comment]
plz try 1.2.5 and feel free to reopen this issue when it doesn't work.
