### ISSUE TITLE
混淆后，安装apk ic_launcher 不显示 & 大体积apk 进行资源混淆操作偶发性失败

### ISSUE THREAD

**Issue by zhEdward** [shwenzhang/AndResGuard#131]
一个issue（#130） 提一个问题，所以我分开下！  

操作环境: 
   - cygwin 
  - 7-Zip (a) [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04
  - `tool_output/` 下的 7z 可执行文件
 -  andResGuard 1.1.16 

  **系统已经正确配置 7z 和 zipalign 的环境变量**

1. 【在 cygwin中操作】使用 `build_apk.sh` 对一个将近 90MB 的apk（代码部分混淆过） 处理 在 repackage 7z时候会出错 偶发性报错（apk体积小的到没出现过该情况，是否和 `-mx0` 有关) ，对于可能是 `7za` 版本不同导致，我也分别测试了 均会偶发如下的 `exception`

```sh
$ ./build_apk.sh
special configFile file path: D:\AndResGuard\tool_output\config.xml
special output directory path: D:\AndResGuard\tool_output\outapk
reading config file, D:\AndResGuard\tool_output\config.xml
mKeepRoot false
[AndResGuard] begin: outapk, qinjingling.apk
unziping apk to D:\AndResGuard\tool_output\outapk\temp
decoding resources.arsc
parse to get the exist names in the resouces.arsc first
reading packagename fxyy.fjnuit.Activity
resources mapping file D:\AndResGuard\tool_output\outapk\resource_mapping_qinjingling.txt done
writing new resources.arsc
resources.arsc Character Encoding: utf-8
general unsigned apk: qinjingling_unsigned.apk
DestResDir 3359 rawResDir 3359
signing apk: qinjingling_signed.apk
signature Algorithm is: SHA1withRSA
use 7zip to repackage: qinjingling_signed_7zip.apk, will cost much more time
[addStoredFileIn7Zip]rewrite the stored file into the 7zip, file count:308
java.io.IOException: [use7zApk]7z repackage signed apk fail,you must install 7z command line version first, linux: p7zip, window: 7za, path=D:\AndResGuard\tool_output\outapk\qinjingling_signed_7zip.apk
        at com.tencent.mm.androlib.ResourceApkBuilder.use7zApk(ResourceApkBuilder.java:97)
        at com.tencent.mm.androlib.ResourceApkBuilder.buildApk(ResourceApkBuilder.java:50)
        at com.tencent.mm.resourceproguard.Main.buildApk(Main.java:94)
        at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:71)
        at com.tencent.mm.resourceproguard.cli.CliMain.run(CliMain.java:193)
        at com.tencent.mm.resourceproguard.cli.CliMain.main(CliMain.java:37)

```

2. 【疑问】【同`cygwin` 操作】和  #76 的 issue 有点类似， 在检查了`微信` , `网易云音乐` (好像是对 APP 图标 进行白名单保护(因为res 根路径是被混淆了 )，我也尝试在 `config.xml` 添加

```xml 

<issue id="whitelist" isactive="true">
  <!-- 全部位于  mipmap-<qualifiers>中 -->
  <path value="<your_package_name>.R.drawable.ic_launcher"/> 
 </issue>

```
 通过`shell` 命令，再安装apk，无法正确显示 `ic_launcher` (我在公司的三四个项目上试验过均出现), 但是如果改用 `keepmapping` 来控制（设置 `whitelist`中 `isactive="false"`） 如下

```xml
 <issue id="keepmapping" isactive="true">
        <!-- 来自 AndResGuard-example\app-->
        <path value="resource_mapping.txt"/>
 </issue>
```

再次执行完 `build_apk.sh` 。再安装 图标均可以正常显示，但 `res/***` 根路径被保留 和  微信/网易云音乐 的不一样, 这里就不太理解（你们是怎么配置的 实现 混淆了根路径 但 图标还可以显示出来）,

还有一个**疑点** 上面 `path value` 使用下面 的 `resource_mapping_bak.txt`替代 也是可以（正常显示图标），似乎图标存放( 在`mipmap-<qualifiers>` )的位置和 该 资源 `mapping`文件 配置的内容(  `drawable-<qualifiers>` 不混淆 父路径)无关系。 

`resource_mapping_bak.txt`文件

```txt
res path mapping:
    res/drawable-hdpi-v4 -> res/drawable-hdpi-v4
    res/drawable-mdpi-v4 -> res/drawable-mdpi-v4
    res/drawable-xhdpi-v4 -> res/drawable-xhdpi-v4
    res/drawable-xxhdpi-v4 -> res/drawable-xxhdpi-v4
    res/drawable-xxxhdpi-v4 -> res/drawable-xxxhdpi-v4
```

PS: 第2点的问题 git clone 下来项目  在AS中 也类似配置测试过，也会出现该点描述的疑问 

```groovy
andResGuard {
    //  method1:放开这句 注释下句 logo的图标且白名单不做保护， 安装完可以正常显示
    //mappingFile = file("./resource_mapping.txt")
    mappingFile = null
    use7zip = true
    useSign = true
    keepRoot = false
    // add <yourpackagename>.R.drawable.icon into whitelist.
    // because the launcher will get the icon with his name
    whiteList = [
             //method2: 上面 mappingFile =null ,添加 图标到白名单 安装完，不能正常显示
            "R.mipmap.ic_launcher",
            //https://docs.fabric.io/android/crashlytics/build-tools.html
            "R.string.com.crashlytics.*"
    ]
    compressFilePattern = [
            "*.png",
            "*.jpg",
            "*.jpeg",
            "*.gif",
            "resources.arsc"
    ]
    sevenzip {
       //这里也是 分别测试 以下两种7z 版本
        artifact = 'com.tencent.mm:SevenZip:1.1.16'//(v15.04)
        ///usr/local/bin/7za
        //path = "D:\\E.D.K.Supremacy\\7-Zip\\x64\\7za.exe"(v16.04)
    }
} 
```

**Comment by simpleton** [comment]
@zhEdward 多谢你详细的issue。
这里图标问题是一个兼容性问题，因为有的平台、ROM是通过绝对路径来读取图标的，所以要使用keepmapping。白名单只是可以保证资源名不被混淆，而keepmapping可以很细粒度的保证整个路径不被混淆。

微信可以work可能是ROM对微信做了特别的适配

**Comment by simpleton** [comment]
7z的问题，你使用zip也会出现么？

**Comment by zhEdward** [comment]
>7z的问题，你使用zip也会出现么？
是指在该位置
```java
  ProcessBuilder pb = new ProcessBuilder(cmd, "a", "-tzip", mSignedWith7ZipApk.getAbsolutePath(), storedParentName, "-mx0");
   Process pro = pb.start();
```

使用 zip 命令 进行 repackage的意思吗？

**Comment by simpleton** [comment]
```gradle
andResGuard {
   ......
   // 这里可以设置成false
    use7zip = true
   ......
}
```

**Comment by zhEdward** [comment]
90MB 的项目比较旧，我直接在 `config.xml` 中 禁用 `<seventzip value="false"/>`  用 `build_apk.sh` 不会出现 我第一点提到的问题

**Comment by zhEdward** [comment]
> 微信可以work可能是ROM对微信做了特别的适配

  我只使用  白名单保护，且把 ` applicationId = com.tencent.mm ` (伪装成微信)在国内某小厂 `rom` 的 设备上 安装 图标还是无法正常显示（但安装 微信 app 可以显示） ，是否可以得出 并不是rom 对 com.tencent.mm 的apk 进行了"适配"呢。



> 还有一个疑点 上面 path value 使用下面 的 resource_mapping_bak.txt替代 也是可以（正常显示图标），似乎图标存放( 在mipmap-<qualifiers> )的位置和 该 资源 mapping文件 配置的内容( drawable-<qualifiers> 不混淆 父路径)无关系。

这个问题也是 我 比较疑惑的

**Comment by simpleton** [comment]
google推荐把图片放到mipmap folder下。
https://android-developers.googleblog.com/2014/10/getting-your-apps-ready-for-nexus-6-and.html

**Comment by zhEdward** [comment]
您好 @simpleton blog我看了，和我的疑惑不相关，就拿这项目中`AndResGuard-example`来说，图标放在 `mipmap-<qulifiers>`中 )，我用  `resource_mapping_bak.txt`（配置的内容 开头有贴出来） 做测试 。图标也都可以显示

```groovy

andResGuard {
    //mappingFile = file("./resource_mapping.txt")
    mappingFile = file("./resource_mapping_bak.txt")
    use7zip = true
    useSign = true
    keepRoot = false
    // add <yourpackagename>.R.drawable.icon into whitelist.
    // because the launcher will get the icon with his name
    whiteList = [
            //自带的看不出效果。请使用其他icon替代
            //"R.mipmap.ic_launcher"
            //https://docs.fabric.io/android/crashlytics/build-tools.html
            "R.string.com.crashlytics.*"
    ]
    compressFilePattern = [
            "*.png",
            "*.jpg",
            "*.jpeg",
            "*.gif",
            "resources.arsc"
    ]
    sevenzip {
        artifact = 'com.tencent.mm:SevenZip:1.1.16'
    }
}

````

**不解地方**是 `mappingFile`不混淆的资源路径( drawable  ) 和 图标的在项目路径( mipmap )  不一致，,但也可以 达到同样效果? 

可能说的有点绕。不知道是否把疑问点描述清楚 :)

**Comment by simpleton** [comment]
没太理解你的不解，sample中`mappingFile`的内容是:
```
res path mapping:
    res/mipmap-hdpi-v4 -> res/mipmap-hdpi-v4
    res/mipmap-mdpi-v4 -> res/mipmap-mdpi-v4
    res/mipmap-xhdpi-v4 -> res/mipmap-xhdpi-v4
    res/mipmap-xxhdpi-v4 -> res/mipmap-xxhdpi-v4
    res/mipmap-xxxhdpi-v4 -> res/mipmap-xxxhdpi-v4
```
和路径一致呀。

**Comment by zhEdward** [comment]
@simpleton 是这样的 sample中`resoucre_mapping.txt`中内容 替换如下内容，做测试。
```java
res path mapping:
    res/drawable-hdpi-v4 -> res/drawable-hdpi-v4
    res/drawable-mdpi-v4 -> res/drawable-mdpi-v4
    res/drawable-xhdpi-v4 -> res/drawable-xhdpi-v4
    res/drawable-xxhdpi-v4 -> res/drawable-xxhdpi-v4
    res/drawable-xxxhdpi-v4 -> res/drawable-xxxhdpi-v4

```
，`mapping`中 无论是 不混淆 `drawable` 还是不混淆 `mipmap`资源路径 对最终结果都一样，那不就是说 这 `resoucre_mapping.txt`文件我可以随意填一种不混淆规则就好了？

**Comment by simpleton** [comment]
我的理解是这2个没什么联系，至少在AndResGuard中没有任何特殊的处理，只是根据你写的规则去keep相应路径。

另外7zip的问题，我这边暂时没有环境可以复现你的问题，你那边还有更多线索么？

**Comment by zhEdward** [comment]
@simpleton  在公司的 Mac 上测试了（执行 shell命令的方式），`7z（v16.04）` repackage 这一步没问题，暂且认为是**个案**。

关于 “resource_mapping.txt”的混淆 icon的问题，我再看看相关资料，看能解决我的那个疑惑， 暂且先 close issue
