### ISSUE TITLE
使用jks之后出现NPE错误

### ISSUE THREAD

**Issue by fengqingxiuyi** [shwenzhang/AndResGuard#141]
错误信息：
java.lang.NullPointerException
	at com.tencent.mm.androlib.ResourceApkBuilder.getSignatureAlgorithm(ResourceApkBuilder.java:108)
	at com.tencent.mm.androlib.ResourceApkBuilder.signApk(ResourceApkBuilder.java:132)
	at com.tencent.mm.androlib.ResourceApkBuilder.buildApk(ResourceApkBuilder.java:49)
	at com.tencent.mm.resourceproguard.Main.buildApk(Main.java:94)
	at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:71)
	at com.tencent.mm.resourceproguard.cli.CliMain.run(CliMain.java:193)
	at com.tencent.mm.resourceproguard.cli.CliMain.main(CliMain.java:37)
java.io.IOException: Can't Generate signed APK. Plz check your sign info is correct.
	at com.tencent.mm.androlib.ResourceApkBuilder.signApk(ResourceApkBuilder.java:159)
	at com.tencent.mm.androlib.ResourceApkBuilder.buildApk(ResourceApkBuilder.java:49)
	at com.tencent.mm.resourceproguard.Main.buildApk(Main.java:94)
	at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:71)
	at com.tencent.mm.resourceproguard.cli.CliMain.run(CliMain.java:193)
	at com.tencent.mm.resourceproguard.cli.CliMain.main(CliMain.java:37)

**Comment by fengqingxiuyi** [comment]
使用keystore没有问题

**Comment by simpleton** [comment]
麻烦问下你使用的是什么类型的key,可否提供一个sample给我debug呢？

**Comment by fengqingxiuyi** [comment]
先描述一下我的操作过程：我通过java -jar andresguard.jar …的方式打包，需要在config.xml中配置签名信息，如果我用debug.keystore签名打包不会报错，一切正常，如果我用release.jks签名打包，会出现之前评论的任务栈信息

**Comment by fengqingxiuyi** [comment]
然后不懂你说的类型指什么？sample的话再说，我看看能不能弄一个测试的release key

**Comment by fengqingxiuyi** [comment]
我今天重新打包了一下可以了，不知道是因为什么。。。。
