### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by huopochuan** [shwenzhang/AndResGuard#152]
java.lang.NullPointerException
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.isToProguardFile(ARSCDecoder.java:868)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:393)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:295)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:201)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:116)
	at com.tencent.mm.androlib.ApkDecoder.decode(ApkDecoder.java:191)
	at com.tencent.mm.resourceproguard.Main.decodeResource(Main.java:87)
	at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:71)
	at com.tencent.mm.resourceproguard.cli.CliMain.run(CliMain.java:194)
	at com.tencent.mm.resourceproguard.cli.CliMain.main(CliMain.java:38)

**Comment by simpleton** [comment]
@huopochuan Which version are you using? Could you send me the original apk file which causes the NPE? My email address is `sunsj1231@gmail.com`

**Comment by simpleton** [comment]
这里先关闭了，重现问题了欢迎随时打开。
