### ISSUE TITLE
使用版本1.2.2AndResGuard打包失败

### ISSUE THREAD

**Issue by KIDNG** [shwenzhang/AndResGuard#153]
使用1.2.2版本打包时出现(回退版本为1.1.9时可以打包成功)
Warning:Console uses unknown character encoding: cp0. Using GBK instead
错误信息：
`warning: Console uses unknown character encoding: cp0. Using GBK instead
Failed to load signer "signer #1"
java.io.IOException: Keystore was tampered with, or password was incorrect
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at apksigner.ApkSignerTool$SignerParams.loadKeyStoreFromFile(ApkSignerTool.java:734)
	at apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCertsFromKeyStore(ApkSignerTool.java:636)
	at apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCerts(ApkSignerTool.java:580)
	at apksigner.ApkSignerTool$SignerParams.access$200(ApkSignerTool.java:534)
	at apksigner.ApkSignerTool.sign(ApkSignerTool.java:229)
	at apksigner.ApkSignerTool.main(ApkSignerTool.java:87)
	at com.tencent.mm.androlib.ResourceApkBuilder.signWithV2sign(ResourceApkBuilder.java:184)
	at com.tencent.mm.androlib.ResourceApkBuilder.signApkV2(ResourceApkBuilder.java:167)`

**Comment by simpleton** [comment]
@KIDNG 可以麻烦尝试下关闭v2签名，使用1.2.2版本试一下么？
`v2SigningEnabled false`

**Comment by simpleton** [comment]
@KIDNG 应该是你的签名和新的apksignv2不兼容造成的。你这里可以简单关闭v2签名来work。
如果你有方法可以复现有问题的签名麻烦告知一下我。
PS:另外下个版本如果遇到这个问题，我这边会自动降级处理（使用v1签名）。

**Comment by KIDNG** [comment]
嗯，在signingConfigs中添加`v2SigningEnabled false`后可以正常打包。

**Comment by simpleton** [comment]
@KIDNG 那可以确认是您签名不兼容我这边使用的v2scheme库。可以提供一份您签名的生成方法么？

**Comment by KIDNG** [comment]
直接在Android Studio中生成的，AS版本2.3.1

**Comment by simpleton** [comment]
@KIDNG 您可否给我提供一个测试用的key呢？我这边生成是OK的。多谢了

**Comment by KIDNG** [comment]
好的，对应jks及配置以发至您邮箱：sunsj1231@gmail.com 了。
