### ISSUE TITLE
7zip打包后AssetManager#list(String path) 返回数组第一个索引为空字符串

### ISSUE THREAD

**Issue by c86y** [shwenzhang/AndResGuard#162]
#125 曾经提到过这个问题，没看到解决方案。
在1.2.3上我复现了此问题，目前发现只有7zip打包后才会出现，调用*AssetManager#list(String path)*返回如下的数组，首个元素为空字符串。
**[, Info, Resource]**
而且经过验证7zip无论是使用plugin内部artifact配置的，还是使用mac自带的都有问题。
gradle 配置如下
'''
sevenzip {
        artifact = "com.tencent.mm:SevenZip:${ANDRESGUARD_VERSION}"
        //path = "/usr/local/bin/7za"
    }
'''

**Comment by simpleton** [comment]
@c86y 可否提供一份7zip的安装包和andresguard之前的安装包让我debug下呢？

**Comment by c86y** [comment]
zip里放了三个包：
andresguard之前的包：app-ax-ay-universal-release.apk
andresguard没用7zip的包：app-ax-ay-universal-release_signed_aligned.apk
andresguard用了7zip的包：app-ax-ay-universal-release_signed_7zip_aligned.apk

**Comment by c86y** [comment]
@simpleton 
zip里放了三个包：
andresguard之前的包：app-ax-ay-universal-release.apk
andresguard没用7zip的包：app-ax-ay-universal-release_signed_aligned.apk
andresguard用了7zip的包：app-ax-ay-universal-release_signed_7zip_aligned.apk


[issue#162.zip](https://github.com/shwenzhang/AndResGuard/files/1057395/issue.162.zip)

**Comment by simpleton** [comment]
收到，我稍晚排查一下。

**Comment by c86y** [comment]
@simpleton 
这个问题应该比较好复现，我随手写个demo也有这个问题

**Comment by simpleton** [comment]
方便的话，可以把demo也发我。是有且只有7zip包会出问题？

On Jun 7, 2017 5:00 PM, "c86y" <notifications@github.com> wrote:

@simpleton <https://github.com/simpleton>
这个问题应该比较好复现，我随手写个demo也有这个问题

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/shwenzhang/AndResGuard/issues/162#issuecomment-306734651>,
or mute the thread

**Comment by c86y** [comment]
[AndResGuard-example.zip](https://github.com/shwenzhang/AndResGuard/files/1057656/AndResGuard-example.zip)
@simpleton 
这个是基于example改的，可以试试看

**Comment by c86y** [comment]
hi，这个问题最近有什么进展吗？

**Comment by simpleton** [comment]
@c86y 不好意思，debug下来还没有什么解决的思路。 @shwenzhang

**Comment by c86y** [comment]
建议先在README里加下7zip的这个issue，免得其他人再踩坑。微信确实在使用这套7zip的压缩方案吗？之前没有遇到问题？

**Comment by simpleton** [comment]
@c86y 我现在没有在微信团队了，当时是采用了7zip的方案的。现在tinker也在引这边的7zip的jcenter repo。 不过后来又了v2签名，是不能用7zip压缩的了。不知道现在采用了什么方案。
@shwenzhang 来解答下

另外flavor是支持的，dimension没有支持。欢迎pr

**Comment by c86y** [comment]
OK

**Comment by zhenghuiguo** [comment]
gradle版本是2.3.3  AndResGuard-gradle-plugin:1.2.6 同步后在gradle -tasks 中没有生成andresproruard 文件夹是什么原因呢？

**Comment by simpleton** [comment]
@zhenghuiguo 不要再不相关的issue下跟帖提问。
PS: 现在的task group叫做andresguard

**Comment by zhuwenfeng** [comment]
看起来assets目录下文件也都被压缩，可以配置assets文件不压缩，只是压缩resource目录下资源吗？？
@simpleton 

java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
at android.content.res.AssetManager.openAssetFd(Native Method)
at android.content.res.AssetManager.openFd(AssetManager.java:390)

**Comment by wangankang** [comment]
@c86y  请问dimension怎么支持的
