### ISSUE TITLE
生成的APK非常小，无法安装

### ISSUE THREAD

**Issue by linsea** [shwenzhang/AndResGuard#170]
你好，我的APK是60多M，结果生成的APK 才100多KB，无法安装，报非法的APK。
我同时使用了以下的参数：
```
java -jar ~/.../AndResGuard-cli-1.1.8.jar \
./official.apk \
-config .../config.xml \
-out ./tmp \
-signature /xxxkeystore xxx xxx xxx  \
-7zip xxx/bin/7za \
-zipalign xxx/zipalign
```
是否不支持这些参数同时使用？

**Comment by simpleton** [comment]
@linsea 建议使用gradle的方式继承，或者更新一下jar的版本。可以把运行的log贴一下，你给出的相关信息还太少，无法诊断问题。

**Comment by linsea** [comment]
没有错误log,执行成功了。我更新下版本再试试。 我使用命令行集成的，因为要使用PackNG打渠道包。

**Comment by linsea** [comment]
以下是1.2.3版本的执行失败的日志 ：
```

andy@uuu:~/share/andres$ java -jar ~/Android/code/myapk/AndResGuard/AndResGuard-cli-1.2.3.jar \
> ./official.apk \
> -config ~/Android/code/myapk/AndResGuard/config.xml \
> -out ./tmp \
> -signature /home/andy/.android/mm.keystore xxxx xxxx xxxx  \
> -7zip ~/Android/code/myapk/AndResGuard/bin/7za \
> -zipalign /home/andy/Android/Sdk/build-tools/23.0.2/zipalign
special configFile file path: /home/andy/Android/code/myapk/AndResGuard/config.xml
special output directory path: /home/andy/share/andres/./tmp
reading config file, /home/andy/Android/code/myapk/AndResGuard/config.xml
mKeepRoot false
[AndResGuard] begin: ./tmp, ./official.apk
unziping apk to /home/andy/share/andres/./tmp/temp
decoding resources.arsc
parse to get the exist names in the resouces.arsc first
reading packagename com.yyy.mm
resources mapping file /home/andy/share/andres/./tmp/xxx.txt done
writing new resources.arsc 
resources.arsc Character Encoding: utf-8
general unsigned apk: mm-origin_unsigned.apk
DestResDir 4651 rawResDir 4651
java.io.IOException: if you want to use 7z, you must enable useSign in the config file first
	at com.tencent.mm.androlib.ResourceApkBuilder.use7zApk(ResourceApkBuilder.java:92)
	at com.tencent.mm.androlib.ResourceApkBuilder.buildApkV1sign(ResourceApkBuilder.java:56)
	at com.tencent.mm.resourceproguard.Main.buildApk(Main.java:103)
	at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:78)
	at com.tencent.mm.resourceproguard.cli.CliMain.run(CliMain.java:195)
	at com.tencent.mm.resourceproguard.cli.CliMain.main(CliMain.java:38)


Usage: java -jar resousceproguard.jar input.apk
if you want to special the output path or config file path, you can input:
Such as: java -jar resousceproguard.jar input.apk -config yourconfig.xml -out output_directory
if you want to special the sign or mapping data, you can input:
Such as: java -jar resousceproguard.jar input.apk -config yourconfig.xml -out output_directory -signature signature_file_path storepass keypass storealias -mapping mapping_file_path
if you want to special 7za or zipalign path, you can input:
Such as: java -jar resousceproguard.jar input.apk -7zip /home/shwenzhang/tools/7za -zipalign/home/shwenzhang/sdk/tools/zipalign
if you just want to repackage an apk compress with 7z:
Such as: java -jar resousceproguard.jar -repackage input.apk
if you want to special the output path, 7za or zipalign path, you can input:
Such as: java -jar resousceproguard.jar -repackage input.apk-out output_directory -7zip /home/shwenzhang/tools/7za -zipalign/home/shwenzhang/sdk/tools/zipalign

Flags:

--help      This message.
-h          short for -help
-out        set the output directory yourself, if not, the default directory is the running location with name of the input file
-config     set the config file yourself, if not, the default path is the running location with name config.xml
-signature  set sign property, following by parameters: signature_file_path storepass keypass storealias
            if you set these, the sign data in the config file will be overlayed
-mapping    set keep mapping property, following by parameters: mapping_file_path
            if you set these, the mapping data in the config file will be overlayed
-7zip       set the 7zip path, such as /home/shwenzhang/tools/7za, window will be end of 7za.exe
-zipalign   set the zipalign, such as /home/shwenzhang/sdk/tools/zipalign, window will be end of zipalign.exe
-repackage  usually, when we build the channeles apk, it may destroy the 7zip.
            so you may need to use 7zip to repackage the apk

if you donot know how to write the config file, look at the comment in the default config.xml
if you want to use 7z, you must install the 7z command line version in window;
sudo apt-get install p7zip-full in linux

```

以下的1.1.8版本的执行成功的日志：
```
andy@uuu:~/share/andres$ java -jar ~/Android/code/myapk/AndResGuard/AndResGuard-cli-1.1.8.jar \
> ./official.apk \
> -config ~/Android/code/myapk/AndResGuard/config.xml \
> -out ./tmp \
> -signature /home/andy/.android/mm.keystore xxxx xxxx xxxx  \
> -7zip ~/Android/code/myapk/AndResGuard/bin/7za \
> -zipalign /home/andy/Android/Sdk/build-tools/23.0.2/zipalign
special configFile file path: /home/andy/Android/code/myapk/AndResGuard/config.xml
special output directory path: /home/andy/share/andres/./tmp
reading config file, /home/andy/Android/code/myapk/AndResGuard/config.xml
mKeepRoot false
resourceprpguard begin
unziping apk to /home/andy/share/andres/./tmp/temp
decoding resources.arsc
parse to get the exist names in the resouces.arsc first
reading packagename com.yyy.mm
resources mapping file /home/andy/share/andres/xxx.txt done
writing new resources.arsc 
resources.arsc Character Encoding: utf-8
general unsigned apk: mm_unsigned.apk
DestResDir 4651 rawResDir 4651
signing apk: mm_signed.apk
use 7zip to repackage: mm_signed_7zip.apk, will cost much more time
[addStoredFileIn7Zip]rewrite the stored file into the 7zip, file count:0
zipaligning apk: mm-origin_signed.apk
zipaligning apk: mm-origin_signed_7zip.apk
resources proguard done, total time cost: 8.338000s
resources proguard done, you can go to file to find the output /home/andy/share/andres/./tmp

```
可以看出什么问题吗？

**Comment by simpleton** [comment]
1.2.3 是因为没在config里配置签名？

**Comment by linsea** [comment]
但是你认真看，我是有指定config文件的：
```
-config ~/Android/code/myapk/AndResGuard/config.xml
```
貌似命令行解析不到这个参数？
而且命令行中使用了-signature参数，config.xml里面的“sign”部分应该被忽略吧。

**Comment by linsea** [comment]
是否可以workaround?  或者能否发布一个小bugfix版本？

**Comment by simpleton** [comment]
我现在还没诊断出你的问题，你要不把apk包直接发我？我看下比较直接。。。

**Comment by linsea** [comment]
你使用随便一个APK，签名使用*SHA1withRSA*，像上面一样指定参数，记得config.xml里的sign部分这样配置：
```
    <issue id="sign" isactive="false">
        <!--the signature file path, in window use \, in linux use /, and the default path is the running location-->
        <path value="/home/xxx.keystore"/>
        <!--storepass-->
        <storepass value="yyy"/>
        <!--keypass-->
        <keypass value="xxx"/>
        <!--alias-->
        <alias value="zzz"/>
    </issue>
```

这样就可以重现bug了。

**Comment by linsea** [comment]
@simpleton 我给你GMAIL邮件了，请查收，谢谢。

**Comment by simpleton** [comment]
@linsea 我上面说的没诊断出的问题是你issue顶楼提出的问题，就是resguard之后apk极小。

至于sign配置的问题，这里文档可能描述的有一点歧义，实现就是命令行和config.xml都可以配置签名内容，如果都配置最终已命令行为准。但是如何你在config.xml里关掉sign，那sign就被disable了。

**Comment by linsea** [comment]
@simpleton 打出的APK极小使用的是1.1.8版本。
使用1.2.3版本，在config.xml里把”sign"的isactive设置为"true"，并且在命令行中指定signature参数后，可以打出的包正常了。（我的sign结点里面的path,storepass等等信息都是乱填的。）

一点建议，如果在命令行中指定了signature参数后，应该直接忽略config.xml里面的整个sign的配置比较合理。还有，sign里面的path的value似乎不能识别“～”打头的表示的用户目录。
