### ISSUE TITLE
jdk1.7打包失败

### ISSUE THREAD

**Issue by Licy5352** [shwenzhang/AndResGuard#178]
Caused by: java.lang.UnsupportedClassVersionError: com/tencent/gradle/AndResGuardPlugin : Unsupported major.minor version 52.0
	at org.gradle.api.internal.plugins.DefaultPluginRegistry$1.load(DefaultPluginRegistry.java:71)
	at org.gradle.api.internal.plugins.DefaultPluginRegistry$1.load(DefaultPluginRegistry.java:51)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 75 more

**Comment by simpleton** [comment]
升级到jdk1.8吧，as最新的版本也只支持到jdk1.8了。

**Comment by imknown** [comment]
为何不用 AS 自带并自荐的 OpenJDK?

**Comment by simpleton** [comment]
@imknown ok，我看看改造下。

**Comment by imknown** [comment]
@simpleton 啊哈哈, 其实我是对楼主说的, 没想到大哥立意更高 :D
