### ISSUE TITLE
com.tencent.mm.androlib.AndrolibException: Could not decode arsc file

### ISSUE THREAD

**Issue by zhyx** [shwenzhang/AndResGuard#2]
com.tencent.mm.androlib.AndrolibException: Could not decode arsc file
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.write(ARSCDecoder.java:75)
        at com.tencent.mm.androlib.ApkDecoder.decode(ApkDecoder.java:182)
        at com.tencent.mm.resourceproguard.Main.run(Main.java:309)
        at com.tencent.mm.resourceproguard.Main.main(Main.java:73)
Caused by: java.io.EOFException
        at java.io.DataInputStream.readFully(DataInputStream.java:197)
        at com.mindprod.ledatastream.LEDataInputStream.readFully(LEDataInputStream.java:201)
        at com.tencent.mm.util.DataInputDelegate.readFully(DataInputDelegate.java:69)
        at com.tencent.mm.util.ExtDataOutput.writeBytes(ExtDataOutput.java:30)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.reWriteTable(ARSCDecoder.java:266)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.writeTable(ARSCDecoder.java:225)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.write(ARSCDecoder.java:72)
        ... 3 more

**Comment by shwenzhang** [comment]
can you send the apk?

**Comment by zhyx** [comment]
@shwenzhang ，给我一个邮箱，我发给你

**Comment by shwenzhang** [comment]
shaowenzhang1986@gmail.com

**Comment by zhyx** [comment]
@shwenzhang 已发，请查收

**Comment by shwenzhang** [comment]
你这个安装包有问题，似乎不是按照官方的格式。然后安装也一样运行不了？

**Comment by shenbuqingyun** [comment]
试试看 更新到最新的包 classpath 'com.tencent.mm:AndResGuard-gradle-plugin:1.2.17'
