### ISSUE TITLE
集成新版本的华为push导致打包失败

### ISSUE THREAD

**Issue by getandset** [shwenzhang/AndResGuard#203]
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.tencent.mm.androlib.res.decoder.StringBlock.writeSpecNameStringBlock(StringBlock.java:155)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.writePackage(ARSCDecoder.java:318)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.writeTable(ARSCDecoder.java:224)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.write(ARSCDecoder.java:127)
	at com.tencent.mm.androlib.ApkDecoder.decode(ApkDecoder.java:196)
	at com.tencent.mm.resourceproguard.Main.decodeResource(Main.java:93)
	at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:77)
	at com.tencent.mm.resourceproguard.Main.run(Main.java:48)
	at com.tencent.mm.resourceproguard.Main.gradleRun(Main.java:36)
	at com.tencent.mm.resourceproguard.Main$gradleRun.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.tencent.gradle.AndResGuardTask$_run_closure3.doCall(AndResGuardTask.groovy:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
	at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.tencent.gradle.AndResGuardTask.run(AndResGuardTask.groovy:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)

华为push的版本为：
 "com.huawei:cloud_base_service:2.5.54",
 "com.huawei:cloud_push_service:2.5.54"

**Comment by simpleton** [comment]
使用的andresguard什么版本呢？请check下是否为最新

**Comment by getandset** [comment]
Andresguard最新1.2.7版本也还是一样出现相同的错误

**Comment by simpleton** [comment]
@getandset 收到，我周末debug下。

**Comment by getandset** [comment]
请问有什么进展吗？

**Comment by simpleton** [comment]
@getandset 最近有点忙，再请稍等几天

**Comment by simpleton** [comment]
@getandset 你提供的maven地址的仓库是什么呢？我这边无法添加这个依赖。可否麻烦在sample上做一个PR, 来集成这个库呢？

**Comment by codeCacher** [comment]
@simpleton 白名单里面加了下面这些东西，打包的时候失败报的上面一样的 ArrayIndexOutOfBoundsException，把下面的其中一个去掉就可以打包成功，这是为啥  ？
    whiteList = [
            "R.layout.*",
            "R.anim.*",
            "R.id.*",
            "R.string.*",
            "R.color.*",
            "R.menu.*",
            "R.style.*",
            "R.xml.*",
            "R.raw.*",
            "R.attr.*",
            "R.drawable.*",
            "R.dimen.*",
            "R.array.*",
            "R.integer.*",
            "R.bool.*",
            "R.animator.*"
    ]

**Comment by simpleton** [comment]
把哪个去掉呢，可否提供一下编译的log,或者你的基础包

**Comment by codeCacher** [comment]
试了一下，我的资源里面没有R.animator,如果去掉R.animator.*的话还是会报ArrayIndexOutOfBoundsException，但是去掉白名单中其他的任何一项就没问题了。另外我做了一个sample,添加了2000项左右的资源文件，打包的时候就会失败，有没有可能是白名单里面筛选出的项太多引起的，我可以提供一个出现崩溃的sample，我要怎么发给你呢

**Comment by simpleton** [comment]
可以发到我邮箱，profile里有。也可以贴在这里

**Comment by codeCacher** [comment]
已发送到sunsj1231@gmail.com，请查收一下

**Comment by codeCacher** [comment]
@simpleton 请问有什么发现吗？

**Comment by simpleton** [comment]
@codeCacher @getandset 可以尝试下`1.2.8-RC2`
造成这个bug的原因是因为有不同的资源使用了相同的名字（比如R.mipmap.abc和R.drawable.abc）,并且有一个keep mapping造成，stringblock预先申请的buffer不足。

**Comment by codeCacher** [comment]
试了一下，1.2.8-RC2已经没有这个问题了，非常感谢大神提供帮助！

**Comment by simpleton** [comment]
这里我先关闭了，如果@getandset 有问题请再打开

**Comment by MaYinjian** [comment]
![image](https://user-images.githubusercontent.com/23403021/32990759-e5676ca8-cd69-11e7-97dd-f1378326083d.png)
我使用 classpath 'com.tencent.mm:AndResGuard-gradle-plugin:1.2.8-RC2'  还是会报这个问题 
java.lang.ArrayIndexOutOfBoundsException: 37258
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder$ProguardStringBuilder.isReplaced(ARSCDecoder.java:997)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:494)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:453)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:405)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:295)
