### ISSUE TITLE
can not found the aligned apk file

### ISSUE THREAD

**Issue by dingshaoran** [shwenzhang/AndResGuard#211]
-->AndResGuard starting! Current thread# id: 83, name: Task worker for ':' Thread 11
unziping apk to /data1/.jenkins/workspace/OwnerRent_release/OwnerRent_release/app/build/outputs/apk/rent/release/AndResGuard_rent_7_v1.1.0_release_14617/temp
decoding resources.arsc
parse to get the exist names in the resouces.arsc first
reading packagename com.xin.ownerrent
resources mapping file /data1/.jenkins/workspace/OwnerRent_release/OwnerRent_release/app/build/outputs/apk/rent/release/AndResGuard_rent_7_v1.1.0_release_14617/resource_mapping_rent_7_v1.1.0_release_14617.txt done
writing new resources.arsc 
resources.arsc Character Encoding: utf-8
General unsigned apk: rent_7_v1.1.0_release_14617_unsigned.apk
add meta file /data1/.jenkins/workspace/OwnerRent_release/OwnerRent_release/app/build/outputs/apk/rent/release/AndResGuard_rent_7_v1.1.0_release_14617/temp/META-INF/CERT.DSA
add meta file /data1/.jenkins/workspace/OwnerRent_release/OwnerRent_release/app/build/outputs/apk/rent/release/AndResGuard_rent_7_v1.1.0_release_14617/temp/META-INF/rxjava.properties
DestResDir 837 rawResDir 837
zipaligning apk: rent_7_v1.1.0_release_14617_unsigned.apk
java.io.IOException: can not found the aligned apk file, the ZipAlign path is correct? path=/data1/.jenkins/workspace/OwnerRent_release/OwnerRent_release/app/build/outputs/apk/rent/release/AndResGuard_rent_7_v1.1.0_release_14617/rent_7_v1.1.0_release_14617_aligned_unsigned.apk
	at com.tencent.mm.androlib.ResourceApkBuilder.alignApk(ResourceApkBuilder.java:283)
	at com.tencent.mm.androlib.ResourceApkBuilder.buildApkWithV2sign(ResourceApkBuilder.java:84)
	at com.tencent.mm.resourceproguard.Main.buildApk(Main.java:109)
	at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:81)
	at com.tencent.mm.resourceproguard.Main.run(Main.java:51)
	at com.tencent.mm.resourceproguard.Main.gradleRun(Main.java:38)
	at com.tencent.mm.resourceproguard.Main$gradleRun.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.tencent.gradle.AndResGuardTask$_run_closure3.doCall(AndResGuardTask.groovy:116)

**Comment by dingshaoran** [comment]
使用打包机jenkins，gradle 4.1  1.2.8

**Comment by simpleton** [comment]
Hi Shaoran,

确认一下本地运行是否work呢？这个确实比较奇怪，看log已经生成unsigned.apk了，确认下jenkins上相关sdk工具都有配置正确，比如zipalign之类的.

BR,
Sim

**Comment by TragedyGo** [comment]
java.io.IOException: can not found the aligned apk file, the ZipAlign path is correct? 
错误不是很明显么，他构建机没有下载ZipAlign或者配置路径apk路径不对
推荐用新版，gradle配置方案，博主这个造福人类

**Comment by simpleton** [comment]
这里先关闭了，如果有更多错误信息提供请重新打开。
