### ISSUE TITLE
OSX Cannot run program "zipalign" 

### ISSUE THREAD

**Issue by bunnyblue** [shwenzhang/AndResGuard#23]
```Java
zipaligning apk: app-release-unaligned_signed.apk
java.io.IOException: Cannot run program "zipalign": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.tencent.mm.androlib.ResourceApkBuilder.alignApk(ResourceApkBuilder.java:195)
	at com.tencent.mm.androlib.ResourceApkBuilder.alignApk(ResourceApkBuilder.java:166)
	at com.tencent.mm.androlib.ResourceApkBuilder.buildApk(ResourceApkBuilder.java:48)
	at com.tencent.mm.resourceproguard.Main.run(Main.java:326)
	at com.tencent.mm.resourceproguard.Main.main(Main.java:67)
Error:java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more
Usage: java -jar resousceproguard.jar input.apk
```
已经加入到path  shell下运行zipalign正常

**Comment by shwenzhang** [comment]
shell跟java的命令行的环境变量不一样一样，可以手动传入zipalign路径
