### ISSUE TITLE
signing apk IOException

### ISSUE THREAD

**Issue by droidwolf** [shwenzhang/AndResGuard#24]
java.io.IOException: Cannot run program "jarsigner": CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at com.tencent.mm.androlib.ResourceApkBuilder.signApk(ResourceApkBuilder.java:135)
        at com.tencent.mm.androlib.ResourceApkBuilder.buildApk(ResourceApkBuilder.java:46)
        at com.tencent.mm.resourceproguard.Main.run(Main.java:326)
        at com.tencent.mm.resourceproguard.Main.main(Main.java:67)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 8 more

**Comment by shwenzhang** [comment]
please install jdk，and add it to the env path

**Comment by droidwolf** [comment]
ths
