### ISSUE TITLE
关于7z压缩的使用

### ISSUE THREAD

**Issue by marlboro3420** [shwenzhang/AndResGuard#25]
7z压缩已经配置了环境变量，而且在7z命令行模式下也可以使用。但是通过这个工具java -jar andresguard-1.1.jar app-release.apk 这样使用的时候，会报

signing apk: app-release_signed.apk
sign apk app-release_signed.apk done, file reduce: 89.360352kb, time cost from begin: 7.542000s
use 7zip to repackage: app-release_signed_7zip.apk, will cost much more time
general the raw 7zip file
java.io.IOException: Cannot run program "7za": CreateProcess error=2, ?????????
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at com.tencent.mm.androlib.ResourceApkBuilder.generalRaw7zip(ResourceApkBuilder.java:346)
        at com.tencent.mm.androlib.ResourceApkBuilder.use7zApk(ResourceApkBuilder.java:85)
        at com.tencent.mm.androlib.ResourceApkBuilder.buildApk(ResourceApkBuilder.java:47)
        at com.tencent.mm.resourceproguard.Main.run(Main.java:326)
        at com.tencent.mm.resourceproguard.Main.main(Main.java:67)
Caused by: java.io.IOException: CreateProcess error=2, ?????????
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 9 more

这样的错误。

config.xml  关于7z的配置是：

 <！--issue id="property" > 
    
         <！--seventzip value= "true" />
         <！--metaname value="META-INF" />
         <！--keeproot value="false" />
     
     <！--/issue>

（在这上面放这段代码时我把注释删掉了，注释是为了显示这段代码，不加注释在这上面不显示Orz）

通过直接使用命令
java -jar andresguard-1.1.jar -repackage app-release_signed.apk -out output_directory -7zip D:\7-Zip\7z.exe -zipalign D:\Android\sdk\android-sdk\build-tools\21.1.2\zipalign.exe

压缩混淆后的APK是可以得，请问这是什么问题造成的呢？

补充：
7z 配置的环境变量： D:\7-Zip  这样配置 命令行是可以使用7z的。如果配置为D:\7-Zip\7z.exe是不能命令行使用7z的

**Comment by shwenzhang** [comment]
用的是7za, 7z的命名行版本

**Comment by marlboro3420** [comment]
好的，谢谢
