### ISSUE TITLE
android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by ideav5** [shwenzhang/AndResGuard#259]
Caused by: android.content.res.Resources$NotFoundException: File r/d/ic_guardian_gif.gif from drawable resource ID #0x7f02017b
        at android.content.res.ResourcesImpl.openRawResourceFd(ResourcesImpl.java:371)
        at android.content.res.Resources.openRawResourceFd(Resources.java:1443)
        at pl.droidsonroids.gif.e.<init>(GifDrawable.java:93)
---------------------------------------------------
	public GifDrawable(@NonNull Resources res, @RawRes @DrawableRes int id) throws NotFoundException, IOException {
		this(res.openRawResourceFd(id));
		final float densityScale = GifViewUtils.getDensityScale(res, id);
		mScaledHeight = (int) (mNativeInfoHandle.getHeight() * densityScale);
		mScaledWidth = (int) (mNativeInfoHandle.getWidth() * densityScale);
	}

 r/d/ic_guardian_gif.gif 这个gif图片是存在这个路径的,但是就是没找到

**Comment by simpleton** [comment]
`pl.droidsonroids.gif`是一个第三方的库么？
可否复现这个问题呢？

**Comment by ideav5** [comment]
是的,就是这个第三方库

**Comment by haoge1214** [comment]
对 Resources.openRawResourceFd(id) 方法就会
ndroid.content.res.Resources$NotFoundException: File r/f/icon_user_level_11.gif from drawable resource ID #0x7f02028f
这些gif 已经加白名单过滤了 文件夹中也存在这些文件

**Comment by jiyewushen** [comment]
同样的bug
```java
 Caused by: android.content.res.Resources$NotFoundException: File r/a_/b.gif from drawable resource ID #0x7f080001
        at android.content.res.ResourcesImpl.openRawResourceFd(ResourcesImpl.java:291)
        at android.content.res.Resources.openRawResourceFd(Resources.java:1267)
        at pl.droidsonroids.gif.c.<init>(GifDrawable.java:95)
```
补充第三方库的地址:https://github.com/koral--/android-gif-drawable

**Comment by W252016021** [comment]
同样的问题，以字符串引用的资源文件，白名单好像没有效果
