### ISSUE TITLE
AndResGuardTask.groovy:83 Crash

### ISSUE THREAD

**Issue by fengshiqian** [shwenzhang/AndResGuard#261]
我使用tinker和AndResGuard，在生成补丁时出现crash，在AndResGuardTask.groovy的第83行，日志
```
Caused by: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
        [class java.lang.String]
        [class java.net.URI]
        at com.tencent.gradle.AndResGuardTask$_run_closure3.doCall(AndResGuardTask.groovy:83)
        at com.tencent.gradle.AndResGuardTask.run(AndResGuardTask.groovy:81)
```
看源码
```
if (StringUtil.isBlank(configuration.sourceApk) && !new File(configuration.sourceApk).exists()) {
                    throw new PathNotExist("Original APK not existed for " + AndResGuardPlugin.USE_APK_TASK_NAME)
}
```
这里的&&是不是应该用||？如果configuration.sourceApk是null，后面new File就会报错，不知道要用File的哪个构造

**Comment by simpleton** [comment]
是的，多谢发现BUG。

另外这里是tinker和AndResGuard结合的例子：https://github.com/TinkerPatch/tinkerpatch-andresguard-sample
