### ISSUE TITLE
Firebase Exception

### ISSUE THREAD

**Issue by mayqlzu** [shwenzhang/AndResGuard#268]
I use google firebase in my project and build with command "gradlew resguardDebug", when I run the app, the code "FirebaseInstanceId().getInstance() throws exception:
```
Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.foo.bar. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
        at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
...
```
In fact, I called "FirebaseApp.initializeApp(Context)" as someone suggests on StackOverflow,
I guess it's because AndResGuard obfuscated my Firebase config file "google-services.json" in directory <project-root>/app/, then, I add "whiteList = [ google-services.json]” in my module's build.gradle，this time, I even can not build it, the error message is:
```
> Task :app:resguardDebug 
java.io.IOException: please write the full package name,eg com.tencent.mm.R.drawable.dfdf, but yours google-services.json

        at com.tencent.mm.resourceproguard.Configuration.addWhiteList(Configuration.java:269)
        at com.tencent.mm.resourceproguard.Configuration.<init>(Configuration.java:130)
        at com.tencent.mm.resourceproguard.Main.loadConfigFromGradle(Main.java:67)
        at com.tencent.mm.resourceproguard.Main.run(Main.java:44)
...
```

Any help is welcome, thanks!

**Comment by mayqlzu** [comment]
fixed, solution is:
 whiteList = [
            // for google-services, you can find these string in app/build/generated/res/google-servies/values/values.xml
            "R.string.google_app_id",
            "R.string.gcm_defaultSenderId",
            "R.string.default_web_client_id",
            "R.string.ga_trackingId",
            "R.string.firebase_database_url",
            "R.string.google_api_key",
            "R.string.google_crash_reporting_api_key",
            "R.string.project_id"
    ]
