### ISSUE TITLE
App Crash with fabric

### ISSUE THREAD

**Issue by simpleton** [shwenzhang/AndResGuard#27]
```
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .     |  | 
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .     |  |
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .     |  |
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .   \ |  | /
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .    \    /
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .     \  /
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .      \/
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
                                                    install an Android build tool and ask a team member to invite you to this app's organization.
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .      /\
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .     /  \
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .    /    \
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .   / |  | \
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .     |  |
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .     |  |
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .     |  |
01-09 06:01:39.570 27119-27119/? E/CrashlyticsCore: .
01-09 06:01:39.575 27119-27119/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.xmonster.letsgo, PID: 27119
                                                   java.lang.RuntimeException: Unable to create application com.xmonster.letsgo.app.XmApplication: io.a.a.a.a.c.m: com.a.a.c.i: 
                                                   This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
                                                   install an Android build tool and ask a team member to invite you to this app's organization.
                                                   
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
                                                       at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: io.a.a.a.a.c.m: com.a.a.c.i: 
                                                   This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
                                                   install an Android build tool and ask a team member to invite you to this app's organization.
                                                   
                                                       at com.a.a.c.f.a(SourceFile:297)
                                                       at com.a.a.c.f.e_(SourceFile:231)
                                                       at io.a.a.a.h.b(SourceFile:44)
                                                       at io.a.a.a.a.c.a.a(SourceFile:611)
                                                       at io.a.a.a.a.c.f.a(SourceFile:43)
                                                       at io.a.a.a.i.w(SourceFile:66)
                                                       at io.a.a.a.c.a(SourceFile:431)
                                                       at io.a.a.a.c.g(SourceFile:375)
                                                       at io.a.a.a.c.c(SourceFile:332)
                                                       at io.a.a.a.c.a(SourceFile:303)
                                                       at com.xmonster.letsgo.app.XmApplication.e(SourceFile:113)
                                                       at com.xmonster.letsgo.app.XmApplication.d(SourceFile:89)
                                                       at com.xmonster.letsgo.app.XmApplication.onCreate(SourceFile:79)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                       	... 8 more
                                                    Caused by: com.a.a.c.i: 
                                                   This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
                                                   install an Android build tool and ask a team member to invite you to this app's organization.
                                                   
                                                       at com.a.a.c.a.a(SourceFile:59)
                                                       at com.a.a.c.f.b(SourceFile:336)
                                                       at com.a.a.c.f.a(SourceFile:255)
                                                       	... 22 more
```

**Comment by shwenzhang** [comment]
需要将 fabric用到的资源添加到白名单中
