### ISSUE TITLE
生成 新的resources.arsc 错误

### ISSUE THREAD

**Issue by caoguodong** [shwenzhang/AndResGuard#274]
**error log：**
parse to get the exist names in the resouces.arsc first
reading packagename xxx.xxx.xxx
resources mapping file /xxx/xxx/abc/input/resource_mapping_input.txt done
copy res file not in resources.arsc file:drawable-xxhdpi-v4/ic_launcher.png
copy res file not in resources.arsc file:drawable-xhdpi-v4/ic_launcher.png
writing new resources.arsc 
resources.arsc Character Encoding: utf-16
java.lang.NullPointerException
	at com.tencent.mm.util.ExtDataOutput.writeIntArray(ExtDataOutput.java:15)
	at com.tencent.mm.androlib.res.decoder.StringBlock.writeTableNameStringBlock(StringBlock.java:324)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.writeTable(ARSCDecoder.java:215)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.write(ARSCDecoder.java:127)
	at com.tencent.mm.androlib.ApkDecoder.decode(ApkDecoder.java:194)
	at com.tencent.mm.resourceproguard.Main.decodeResource(Main.java:99)
	at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:84)
	at com.tencent.mm.resourceproguard.cli.CliMain.run(CliMain.java:205)
	at com.tencent.mm.resourceproguard.cli.CliMain.main(CliMain.java:41)

**apk build tool**：dexguard
**use version**：AndResGuard-cli-1.2.12
**use type**：command line
**command**：java -jar AndResGuard-cli-1.2.12.jar input.apk -zipalign /xxx/xxx/xxx/zipalign
**notice**: has installed 7z

**Comment by simpleton** [comment]
dexguard已经有类似功能，建议不要同时使用

**Comment by caoguodong** [comment]
其实只想用7z做一下极限的缩包
