### ISSUE TITLE
使用jenkins混淆失败

### ISSUE THREAD

**Issue by chinasunwukong** [shwenzhang/AndResGuard#296]
unziping apk to /var/jenkins_home/jobs/workspace/android/build/outputs/apk/release/**/temp
decoding resources.arsc
parse to get the exist names in the resouces.arsc first
reading packagename com.****
java.lang.NullPointerException
at com.tencent.mm.androlib.res.decoder.ARSCDecoder.isToResguardFile(ARSCDecoder.java:887)
at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:411)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:302)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:195)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:111)
	at com.tencent.mm.androlib.ApkDecoder.decode(ApkDecoder.java:182)
	at com.tencent.mm.resourceproguard.Main.decodeResource(Main.java:113)
	at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:97)
	at com.tencent.mm.resourceproguard.Main.run(Main.java:56)
	at com.tencent.mm.resourceproguard.Main.gradleRun(Main.java:39)
	at com.tencent.mm.resourceproguard.Main$gradleRun.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.tencent.gradle.AndResGuardTask.RunGradleTask(AndResGuardTask.groovy:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at com.tencent.gradle.AndResGuardTask$_run_closure3.doCall(AndResGuardTask.groovy:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by simpleton** [comment]
@baiting123 可否提供一下你使用工具链得版本？

**Comment by baiting123** [comment]
classpath 'com.android.tools.build:gradle:3.0.0'

**Comment by baiting123** [comment]
在本地使用resguardRelease没有问题，使用远程jenkins运行resguardRelease就有问题。

**Comment by simpleton** [comment]
应该是本地环境的问题
