### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by cxMax** [shwenzhang/AndResGuard#299]
-->AndResGuard starting! Current thread# id: 32, name: Task worker for ':'
unziping apk to /Users/caixi/AndroidStudioProjects/android_hox/app/build/outputs/apk/DevTest/debug/AndResGuard_app-DevTest-debug/temp
java.io.FileNotFoundException: /Users/caixi/AndroidStudioProjects/android_hox/app/build/outputs/apk/DevTest/debug/AndResGuard_app-DevTest-debug/temp/org/qiyi (Not a directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at com.tencent.mm.util.FileOperation.unZipAPk(FileOperation.java:175)
	at com.tencent.mm.androlib.ApkDecoder.ensureFilePath(ApkDecoder.java:84)
	at com.tencent.mm.androlib.ApkDecoder.decode(ApkDecoder.java:177)
	at com.tencent.mm.resourceproguard.Main.decodeResource(Main.java:113)
	at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:97)
	at com.tencent.mm.resourceproguard.Main.run(Main.java:56)
	at com.tencent.mm.resourceproguard.Main.gradleRun(Main.java:39)
	at com.tencent.mm.resourceproguard.Main$gradleRun.call(Unknown Source)

**Comment by cxMax** [comment]
你好， 能帮忙定位下是什么问题吗， 项目里面有引用到， https://github.com/iqiyi/Andromeda

**Comment by simpleton** [comment]
@cxMax 能描述一下如何复现么？

**Comment by cxMax** [comment]
![image](https://user-images.githubusercontent.com/17964075/49981575-7996c700-ff93-11e8-8502-558e6d7a1322.png)
使用这个库https://github.com/iqiyi/Andromeda， 编译的apk如上图。
然后执行AndResGuard就会报上面的异常。
我尝试使用Redex也出现了同样的异常报错
