### ISSUE TITLE
单 res 文件夹路径 keep

### ISSUE THREAD

**Issue by jokermonn** [shwenzhang/AndResGuard#302]
# 问题复现：
```
resource_mapping.txt:

res path mapping:
    res/anim -> r/c
    res/anim-v21 -> r/d
    res/animator -> r/e
    res/color -> r/f
    res/drawable -> res/drawable      // 希望只 keep res/drawable 路径
```
```
andResGuard {
   keepRoot = true  // 如果为 false 将会报错
}
```

# 期望状态：

只 keep res/drawable 路径
解压后资源文件夹结构为

├ res
├━ drawable
├ r
├━ c
├━ d
├━ e
├━ f
├ class.dex
├ AndroidManifest.xml
└ .....

# 问题原因：

![image](https://user-images.githubusercontent.com/16160722/50267625-d64a2400-0462-11e9-82ee-2beaac0a66e7.png)

keep 了 res/drawable 路径的话将会导致 if 语句中 `FileOperation.getlist(destResDir)` 为 false（此时 destResDir 为 dir，有且仅有 drawable 一个子文件夹），所以走到第二个 if 的时候将会不等并抛出异常，不知道这是一个 feature 还是 bug？

**Comment by TragedyGo** [comment]
您好，请问keep单个路径问题解决了么

**Comment by jokermonn** [comment]
没有

**Comment by TragedyGo** [comment]
AssetFileDescriptor var1 = this.getContext().getResources().getAssets().openFd("xxxx_yyyy.jpg");
            MappedByteBuffer buffer = (new FileInputStream(var1.getFileDescriptor())).getChannel().map(FileChannel.MapMode.READ_ONLY,
                    var1.getStartOffset(), var1.getDeclaredLength());
------------------------------------------------------------------------------------------
2019-04-24 16:32:28.251 7325-7325/? W/System.err: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
2019-04-24 16:32:28.251 7325-7325/? W/System.err:     at android.content.res.AssetManager.openAssetFd(Native Method)
2019-04-24 16:32:28.251 7325-7325/? W/System.err:     at android.content.res.AssetManager.openFd(AssetManager.java:406)

----------------------------------------------------------------------------------------

老哥再加个keep需求，压缩jpeg什么的也加个路径keep吧，我直接魔改了该项目，加了个列表，跟上面一样，看了下代码writerList只能防止混淆，但我assert中某些jpeg被压缩了，但我又不想去掉所有能压缩的jpeg，最近接谷歌翻译sdk发现的。

**Comment by JasonGaoH** [comment]
好像还是没有解决
