### ISSUE TITLE
7zip重新打包报错：java.lang.RuntimeException: System ERROR: ???????????????????????????

### ISSUE THREAD

**Issue by mmd-panda** [shwenzhang/AndResGuard#305]
use 7zip to repackage: myluban-cloud-release_7zip_unsigned.apk, will cost much more time
[addStoredFileIn7Zip]rewrite the stored file into the 7zip, file count: 1
C:/Users/72977/.gradle/caches/modules-2/files-2.1/com.tencent.mm/SevenZip/1.2.15/4786999cf29d8e3b0c39a80359b5127bda36132a/SevenZip-1.2.15-windows-x86_64.exe Failed! Please check your signature file.

java.lang.RuntimeException: 

System ERROR:
???????????????????????????

	at com.tencent.mm.util.Utils.runCmd(Utils.java:69)
	at com.tencent.mm.androlib.ResourceApkBuilder.addStoredFileIn7Zip(ResourceApkBuilder.java:391)
	at com.tencent.mm.androlib.ResourceApkBuilder.use7zApk(ResourceApkBuilder.java:152)
	at com.tencent.mm.androlib.ResourceApkBuilder.buildApkWithV2sign(ResourceApkBuilder.java:76)
	at com.tencent.mm.resourceproguard.Main.buildApk(Main.java:129)
	at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:98)
	at com.tencent.mm.resourceproguard.Main.run(Main.java:56)
	at com.tencent.mm.resourceproguard.Main.gradleRun(Main.java:39)
	at com.tencent.mm.resourceproguard.Main$gradleRun.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.tencent.gradle.AndResGuardTask.RunGradleTask(AndResGuardTask.groovy:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at com.tencent.gradle.AndResGuardTask$_run_closure3.doCall(AndResGuardTask.groovy:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2040)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2025)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2066)
	at org.codehaus.groovy.runtime.dgm$163.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.tencent.gradle.AndResGuardTask.run(AndResGuardTask.groovy:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
9:08:10: Task execution finished 'resguardCloudRelease'.

**Comment by simpleton** [comment]
`C:/Users/72977/.gradle/caches/modules-2/files-2.1/com.tencent.mm/SevenZip/1.2.15/4786999cf29d8e3b0c39a80359b5127bda36132a/SevenZip-1.2.15-windows-x86_64.exe`可以试试这个可否运行。

或者自己下载一个7zip，然后直接指定path
```
    sevenzip {
        path = "/usr/local/bin/7za"
    }
```

**Comment by mmd-panda** [comment]
我发现只要修改了and_res_guard.gradle文件之后，必须重启AS才可以，不然还是会报这个错，Sync项目也无效，可能是缓存的问题吧

**Comment by Jimmy-J** [comment]
我使用 windows 10 还是会有这个错误，指定本地下载的 7zip 包也是一样

**Comment by Jimmy-J** [comment]
我重新下载了 16.04 版本的 7zip 打包正常的了，用最新的 19.00 版本会有上面的错误
