### ISSUE TITLE
生成后的APK无法安装

### ISSUE THREAD

**Issue by JokerW** [shwenzhang/AndResGuard#34]
用最简单的方式成功生成了未签名的APK后，该APK无法安装。豌豆荚提示安装失败原因是“该应用签名有问题，无法安装”。我都没有做签名，为什么会这么提示。麻烦帮忙解决下，谢谢了。

**Comment by simpleton** [comment]
如果要发布apk还是要签名的，可以自己生成一个签上即可。

2016-01-25 15:32 GMT+08:00 JokerW <notifications@github.com>:

**Comment by JokerW** [comment]
我们的项目是在eclipse上开发的，所以我用的你们的tool_output那个工具。生成了签名的APK，然后写了混淆签名的配置文件，通过该工具混淆会报以下的错误（我直接把报错的地方截取了）：
signing apk: new_test_signed.apk
java.io.IOException: can not found the signed apk file, is the input sign data c
orrect? path=F:\Good pro\AndResGuard-master\AndResGuard-master\tool_output\outap
k\new_test_signed.apk
        at com.tencent.mm.androlib.ResourceApkBuilder.signApk(ResourceApkBuilder
.java:122)
        at com.tencent.mm.androlib.ResourceApkBuilder.buildApk(ResourceApkBuilde
r.java:46)
        at com.tencent.mm.resourceproguard.Main.buildApk(Main.java:93)
        at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:70)
        at com.tencent.mm.resourceproguard.cli.CliMain.run(CliMain.java:192)
        at com.tencent.mm.resourceproguard.cli.CliMain.main(CliMain.java:36)
签名的配置：config 
<issue id="sign" isactive="true">
        <path value="test_new.keystore"/>
        <storepass value="testpass"/>
        <keypass value="testpass"/>
        <alias value="test"/>
 </issue>
buildAPK.bat:
 java -jar AndResGuard-cli.jar new_test.apk -config config.xml -out outapk -signature test_new.keystore testpass testpass test
我将whitelist，keepmapping， compress的isactive全都置成了false。应该不会因此产生上面的错误吧。而且他一开始打出来了一个unsigned的apk，是无法安装的。谢谢了。

**Comment by simpleton** [comment]
感觉你的反馈，我看一下。

**Comment by JokerW** [comment]
谢谢，是因为路径问题，这个项目的tool_output我本来是放在F:\Good pro\AndResGuard-master \AndResGuard-master\tool_output这个路径下的。运行的时候就报上面的错误，但是我把这个工具放在桌面就能够成功打出来签名的APK，没有那个错误了。好诡异的问题啊。

**Comment by simpleton** [comment]
不客气，这里我先关闭issue了。
