### ISSUE TITLE
packageApplicationProvider该属性找不到.gradle版本5.2.1

### ISSUE THREAD

**Issue by AndyZhaiXXX** [shwenzhang/AndResGuard#340]
Could not get unknown property 'packageApplicationProvider' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl

**Comment by simpleton** [comment]
可否提供一下完整的log

**Comment by AndyZhaiXXX** [comment]
> 可否提供一下完整的log
好的。我的gradle配置是这样的：
andResGuard {
  use7zip = true
  useSign = true
  // 打开这个开关，会keep住所有资源的原始路径，只混淆资源的名字
  keepRoot = true
  // 打开这个开关会合并所有哈希值相同的资源，但请不要过度依赖这个功能去除去冗余资源
  mergeDuplicatedRes = true
  compressFilePattern = [
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.webp"
  ]
  sevenzip {
    artifact = 'com.tencent.mm:SevenZip:1.2.16'
    //path = "/usr/local/bin/7za"
  }
//  finalApkBackupPath = "${project.rootDir}/final_xxx.apk"
}


完整Log如下：

Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'packageApplicationProvider' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.
        at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:86)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
        at com.android.build.gradle.internal.api.ApplicationVariantImpl_Decorated.getProperty(Unknown Source)
        at com.tencent.gradle.AndResGuardTask$_closure2$_closure6$_closure7.doCall(AndResGuardTask.groovy:40)
        at com.tencent.gradle.BuildInfo.toString(BuildInfo.groovy:27)
        at com.tencent.gradle.AndResGuardTask.run(AndResGuardTask.groovy:76)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:672)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$4.run(ExecuteActionsTaskExecuter.java:338)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:327)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:312)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:75)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:158)
        at org.gradle.internal.execution.impl.steps.ExecuteStep.execute(ExecuteStep.java:46)
        at org.gradle.internal.execution.impl.steps.CancelExecutionStep.execute(CancelExecutionStep.java:34)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:69)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.execute(TimeoutStep.java:49)
        at org.gradle.internal.execution.impl.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.impl.steps.CreateOutputsStep.execute(CreateOutputsStep.java:49)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:42)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:28)
        at org.gradle.internal.execution.impl.steps.CacheStep.executeWithoutCache(CacheStep.java:133)
        at org.gradle.internal.execution.impl.steps.CacheStep.lambda$execute$5(CacheStep.java:83)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:82)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:37)
        at org.gradle.internal.execution.impl.steps.PrepareCachingStep.execute(PrepareCachingStep.java:33)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:38)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:23)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:95)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:88)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:34)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:109)
        ... 37 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 28s
1024 actionable tasks: 7 executed, 1017 up-to-date

**Comment by huangjiaqiang** [comment]
> > 可否提供一下完整的log
> > 好的。我的gradle配置是这样的：
> > andResGuard {
> > use7zip = true
> > useSign = true
> > // 打开这个开关，会keep住所有资源的原始路径，只混淆资源的名字
> > keepRoot = true
> > // 打开这个开关会合并所有哈希值相同的资源，但请不要过度依赖这个功能去除去冗余资源
> > mergeDuplicatedRes = true
> > compressFilePattern = [
> > "_.png",
> > "_.jpg",
> > "_.jpeg",
> > "_.gif",
> > "*.webp"
> > ]
> > sevenzip {
> > artifact = 'com.tencent.mm:SevenZip:1.2.16'
> > //path = "/usr/local/bin/7za"
> > }
> > //  finalApkBackupPath = "${project.rootDir}/final_xxx.apk"
> > }
> 
> 完整Log如下：
> 
> Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'packageApplicationProvider' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.
> at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:86)
> at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
> at com.android.build.gradle.internal.api.ApplicationVariantImpl_Decorated.getProperty(Unknown Source)
> at com.tencent.gradle.AndResGuardTask$_closure2$_closure6$_closure7.doCall(AndResGuardTask.groovy:40)
> at com.tencent.gradle.BuildInfo.toString(BuildInfo.groovy:27)
> at com.tencent.gradle.AndResGuardTask.run(AndResGuardTask.groovy:76)
> at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
> at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
> at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
> at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
> at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
> at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:672)
> at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$4.run(ExecuteActionsTaskExecuter.java:338)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
> at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
> at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:327)
> at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:312)
> at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:75)
> at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:158)
> at org.gradle.internal.execution.impl.steps.ExecuteStep.execute(ExecuteStep.java:46)
> at org.gradle.internal.execution.impl.steps.CancelExecutionStep.execute(CancelExecutionStep.java:34)
> at org.gradle.internal.execution.impl.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:69)
> at org.gradle.internal.execution.impl.steps.TimeoutStep.execute(TimeoutStep.java:49)
> at org.gradle.internal.execution.impl.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
> at org.gradle.internal.execution.impl.steps.CreateOutputsStep.execute(CreateOutputsStep.java:49)
> at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:42)
> at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:28)
> at org.gradle.internal.execution.impl.steps.CacheStep.executeWithoutCache(CacheStep.java:133)
> at org.gradle.internal.execution.impl.steps.CacheStep.lambda$execute$5(CacheStep.java:83)
> at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:82)
> at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:37)
> at org.gradle.internal.execution.impl.steps.PrepareCachingStep.execute(PrepareCachingStep.java:33)
> at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:38)
> at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:23)
> at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:95)
> at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:88)
> at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
> at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
> at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:34)
> at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:109)
> ... 37 more
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 28s
> 1024 actionable tasks: 7 executed, 1017 up-to-date

请问下问题是如何解决的

**Comment by mutour** [comment]
我也遇到这个问题，已经解决。问题出在aliyun仓库。参考以下：

使用版本：
com.tencent.mm:AndResGuard-gradle-plugin:1.2.16
gradle 4.6
com.android.tools.build:gradle:3.2.1


首先问题报错：
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'packageApplicationProvider' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.
        at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:86)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
        at com.android.build.gradle.internal.api.ApplicationVariantImpl_Decorated.getProperty(Unknown Source)
        at com.tencent.gradle.AndResGuardTask$_closure2$_closure6$_closure7.doCall(AndResGuardTask.groovy:40)
        at com.tencent.gradle.BuildInfo.toString(BuildInfo.groovy:27)
        ... 44 more

开始以为是gradle版本问题，ApplicationVariantImpl类中确实没有这个东西。


```
repositories {
        maven { url 'http://maven.aliyun.com/nexus/content/groups/public/'} **//////问题所在**
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.tencent.mm:AndResGuard-gradle-plugin:1.2.16'
    }
```

解决办法：
把aliyun仓库地址放到jcenter后面去，这两个仓库下载的AndResGuard-gradle-plugin 1.2.16版本文件大小不一样。https://jcenter.bintray.com仓库下载的问题没有问题

Download http://maven.aliyun.com/nexus/content/groups/public/com/tencent/mm/AndResGuard-gradle-plugin/1.2.16/AndResGuard-gradle-plugin-1.2.16.jar
Download http://maven.aliyun.com/nexus/content/groups/public/com/tencent/mm/AndResGuard-core/1.2.16/AndResGuard-core-1.2.16.jar

Download https://jcenter.bintray.com/com/tencent/mm/AndResGuard-gradle-plugin/1.2.16/AndResGuard-gradle-plugin-1.2.16.jar
Download https://jcenter.bintray.com/com/tencent/mm/AndResGuard-core/1.2.16/AndResGuard-core-1.2.16.jar
