### ISSUE TITLE
【求助】线上偶现的崩溃，图片资源索引无法找到异常

### ISSUE THREAD

**Issue by quelang9** [shwenzhang/AndResGuard#347]
这个崩溃无法复现，崩溃率大概在万分之三左右。
不知道有没有其他人遇到这个崩溃？

 # Platform: android
# OS Version: 4.4.2
# Device: Y4
# RAM Free: 14.6%
# Disk Free: 36.3%
--
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{launcher.LauncherActivity}: android.view.InflateException: Binary XML file line #7: Error inflating class ImageView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)

Caused by android.view.InflateException: Binary XML file line #7: Error inflating class ImageView
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at android.support.v7.app.AppCompatDelegateImpl.b(SourceFile:469)
       at android.support.v7.app.AppCompatActivity.setContentView(SourceFile:140)
       at launcher.LauncherActivity.onCreate(SourceFile:57)
       at android.app.Activity.performCreate(Activity.java:5264)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)

Caused by android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/fh.png from drawable resource ID #0x7f0700c4
       at android.content.res.Resources.loadDrawable(Resources.java:2172)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
       at android.widget.ImageView.<init>(ImageView.java:129)
       at android.support.v7.widget.AppCompatImageView.<init>(SourceFile:72)
       at android.support.v7.widget.AppCompatImageView.<init>(SourceFile:68)
       at android.support.v7.app.AppCompatViewInflater.createImageView(SourceFile:182)
       at android.support.v7.app.AppCompatViewInflater.createView(SourceFile:106)
       at android.support.v7.app.AppCompatDelegateImpl.a(SourceFile:1266)
       at android.support.v7.app.AppCompatDelegateImpl.onCreateView(SourceFile:1316)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at android.support.v7.app.AppCompatDelegateImpl.b(SourceFile:469)
       at android.support.v7.app.AppCompatActivity.setContentView(SourceFile:140)
       at launcher.LauncherActivity.onCreate(SourceFile:57)
       at android.app.Activity.performCreate(Activity.java:5264)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)

Caused by java.io.FileNotFoundException: res/drawable-xxhdpi-v4/fh.png
       at android.content.res.AssetManager.openNonAssetNative(AssetManager.java)
       at android.content.res.AssetManager.openNonAsset(AssetManager.java:421)
       at android.content.res.Resources.loadDrawable(Resources.java:2163)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
       at android.widget.ImageView.<init>(ImageView.java:129)
       at android.support.v7.widget.AppCompatImageView.<init>(SourceFile:72)
       at android.support.v7.widget.AppCompatImageView.<init>(SourceFile:68)
       at android.support.v7.app.AppCompatViewInflater.createImageView(SourceFile:182)
       at android.support.v7.app.AppCompatViewInflater.createView(SourceFile:106)
       at android.support.v7.app.AppCompatDelegateImpl.a(SourceFile:1266)
       at android.support.v7.app.AppCompatDelegateImpl.onCreateView(SourceFile:1316)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at android.support.v7.app.AppCompatDelegateImpl.b(SourceFile:469)
       at android.support.v7.app.AppCompatActivity.setContentView(SourceFile:140)
       at launcher.LauncherActivity.onCreate(SourceFile:57)
       at android.app.Activity.performCreate(Activity.java:5264)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by liyicool** [comment]
你打开了1万次？
