### ISSUE TITLE
使用例子给的配置参数，直接混淆打包运行报IOException，说res和r不相同？

### ISSUE THREAD

**Issue by coolstar1204** [shwenzhang/AndResGuard#363]
`java.io.IOException: the file count of F:\git\xxxx\app\build\outputs\apk\xx\release\AndResGuard_app-xxrelease\temp\res, and the file count of F:\git\xxxx\app\build\outputs\apk\xx\release\AndR
esGuard_app-xxrelease\r is not equal, there must be some problem

        at com.tencent.mm.androlib.ResourceApkBuilder.generalUnsignApk(ResourceApkBuilder.java:332)
        at com.tencent.mm.androlib.ResourceApkBuilder.buildApkWithV2sign(ResourceApkBuilder.java:78)
        at com.tencent.mm.resourceproguard.Main.buildApk(Main.java:129)
        at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:98)
        at com.tencent.mm.resourceproguard.Main.run(Main.java:56)
        at com.tencent.mm.resourceproguard.Main.gradleRun(Main.java:39)
        at com.tencent.mm.resourceproguard.Main$gradleRun.call(Unknown Source)
        at com.tencent.gradle.AndResGuardTask.RunGradleTask(AndResGuardTask.groovy:168)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
`

**Comment by coolstar1204** [comment]
mergeDuplicatedRes = false  就好了。看来是合并了不一样的资源

**Comment by ysbing** [comment]
> mergeDuplicatedRes = false 就好了。看来是合并了不一样的资源

感谢反馈，我跟进看看
