### ISSUE TITLE
Firebase接受推送时崩溃

### ISSUE THREAD

**Issue by lrchao** [shwenzhang/AndResGuard#376]
2019-08-16 16:12:37.063 5019-5119/com.xxx.xxx E/xxx.xxx: Invalid ID 0x00000000.
2019-08-16 16:12:37.066 5019-5119/com.xxx.xxx E/AndroidRuntime: FATAL EXCEPTION: Firebase-MyFirebaseMessagingService
    Process: com.xxx.xxx, PID: 5019
    android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:348)
        at android.content.res.Resources.getString(Resources.java:441)
        at android.content.Context.getString(Context.java:578)
        at com.google.firebase.messaging.zza.zzc(com.google.firebase:firebase-messaging@@19.0.1:243)
        at com.google.firebase.messaging.zza.zza(com.google.firebase:firebase-messaging@@19.0.1:7)
        at com.google.firebase.messaging.zzb.zza(com.google.firebase:firebase-messaging@@19.0.1:34)
        at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@19.0.1:59)
        at com.google.firebase.messaging.zzg.run(com.google.firebase:firebase-messaging@@19.0.1:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:764)

------------------------------------------------------------------------------------------
whiteList = [
            // for your icon
            "R.drawable.icon",
            // for fabric
            "R.string.com.crashlytics.*",
            // for google-services
            "R.string.google_app_id",
            "R.string.gcm_defaultSenderId",
            "R.string.default_web_client_id",
            "R.string.ga_trackingId",
            "R.string.firebase_database_url",
            "R.string.google_api_key",
            "R.string.google_crash_reporting_api_key",
            // Firebase
            "R.string.project_id"
    ]

**Comment by simpleton** [comment]
可以把NotFound的资源加入白名单

**Comment by hanxiaomeme** [comment]
我也遇到了类似的问题 请问你在白名单中加入了什么

**Comment by Xmilton** [comment]
> 我也遇到了类似的问题 请问你在白名单中加入了什么

R.string.fcm_fallback_notification_channel_label
