### ISSUE TITLE
在assets目录中带有中文资源会乱码

### ISSUE THREAD

**Issue by coolstar1204** [shwenzhang/AndResGuard#383]
我们项目表情图标名称，带有中文字符，混淆后，中文变成乱码显示，英文不受影响。
在有些windows机器上，gradle还会报错失败

**Comment by simpleton** [comment]
理想情况下不要使用中文作为任何文件的路径。 你有具体的报错么？

**Comment by gaohang1** [comment]
warning: Console uses unknown character encoding: cp0. Using GBK instead
com.android.apksig.apk.ApkFormatException: Multiple ZIP entries with the same name: assets/emoji/[??????]@2x.png
        at com.android.apksig.ApkSigner.parseZipCentralDirectory(ApkSigner.java:751)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:241)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:193)
        at apksigner.ApkSignerTool.sign(ApkSignerTool.java:273)
        at apksigner.ApkSignerTool.main(ApkSignerTool.java:87)
        at com.tencent.mm.androlib.ResourceApkBuilder.signWithV2sign(ResourceApkBuilder.java:233)
        at com.tencent.mm.androlib.ResourceApkBuilder.signApkV2(ResourceApkBuilder.java:209)
        at com.tencent.mm.androlib.ResourceApkBuilder.buildApkWithV2sign(ResourceApkBuilder.java:90)
        at com.tencent.mm.resourceproguard.Main.buildApk(Main.java:129)
        at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:98)
        at com.tencent.mm.resourceproguard.Main.run(Main.java:56)
        at com.tencent.mm.resourceproguard.Main.gradleRun(Main.java:39)
        at com.tencent.mm.resourceproguard.Main$gradleRun.call(Unknown Source)
