### ISSUE TITLE
使用最新AndResGuard仍然存在com.tencent.mm.androlib.AndrolibException: Could not decode arsc file

### ISSUE THREAD

**Issue by sunboBJ** [shwenzhang/AndResGuard#412]
com.tencent.mm.androlib.AndrolibException: Could not decode arsc file
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.write(ARSCDecoder.java:130)
	at com.tencent.mm.androlib.ApkDecoder.decode(ApkDecoder.java:197)
	at com.tencent.mm.resourceproguard.Main.decodeResource(Main.java:114)
	at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:98)
	at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:84)
	at com.tencent.mm.resourceproguard.cli.CliMain.run(CliMain.java:253)
	at com.tencent.mm.resourceproguard.cli.CliMain.main(CliMain.java:48)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at com.mindprod.ledatastream.LEDataInputStream.readFully(LEDataInputStream.java:180)
	at com.tencent.mm.util.DataInputDelegate.readFully(DataInputDelegate.java:69)
	at com.tencent.mm.util.ExtDataOutput.writeBytes(ExtDataOutput.java:22)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.reWriteTable(ARSCDecoder.java:325)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.writeTable(ARSCDecoder.java:235)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.write(ARSCDecoder.java:128)
	... 6 more

**Comment by YongdongHe** [comment]
1.2.8有这个问题，我们项目升级到1.2.17后没有了

**Comment by sunboBJ** [comment]
已经解决，是项目中设置了aapt的属性，导致id不是正常排序的
