### ISSUE TITLE
[android studio 4.0]No such property: variantConfiguration for class: com.android.build.gradle.internal.variant.ApplicationVariantData

### ISSUE THREAD

**Issue by whoze** [shwenzhang/AndResGuard#420]
No such property: variantConfiguration for class: com.android.build.gradle.internal.variant.ApplicationVariantData

**Comment by whoze** [comment]
Caused by: groovy.lang.MissingPropertyException: No such property: variantConfiguration for class: com.android.build.gradle.internal.variant.ApplicationVariantData
	at com.tencent.gradle.AndResGuardTask$_closure2$_closure6.doCall(AndResGuardTask.groovy:51)
	at com.tencent.gradle.AndResGuardTask$_closure2.doCall(AndResGuardTask.groovy:33)
	at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:105)
	at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:166)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1$1.run(DefaultCollectionCallbackActionDecorator.java:100)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:60)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:97)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:94)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:163)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:198)
	at org.gradle.api.DomainObjectCollection$all.call(Unknown Source)
	at com.tencent.gradle.AndResGuardTask.<init>(AndResGuardTask.groovy:32)
	at com.tencent.gradle.AndResGuardTask_Decorated.<init>(Unknown Source)
	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:1986)
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:468)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstanceWithDisplayName(DependencyInjectingInstantiator.java:50)
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:76)
	... 160 more

**Comment by cjqq354139968** [comment]
I have the same problem, i'm update android plugin with 4.0.0 , and then compiler failed.

A problem occurred configuring project ':app'.
> Could not create task ':app:resguardUseApk'.
   > Could not create task of type 'AndResGuardTask'.
      > No such property: variantConfiguration for class: com.android.build.gradle.internal.variant.ApplicationVariantData

**Comment by whoze** [comment]
https://stackoverflow.com/questions/62075122/no-such-property-variantconfiguration-for-class
In the last gradle Relase ApplicationVariant implement BaseVariant

Instead of

def buildType = variant.variantData.variantConfiguration.buildType.name
Should be

def buildType = variant.buildType.name

希望该项目有人继续尽快跟进啊

**Comment by equationl** [comment]
Same problem

**Comment by zxzxzxygithub** [comment]
+1

**Comment by cyoyochoo** [comment]
+1

**Comment by zhaobozhen** [comment]
Same Problem.

**Comment by cjqq354139968** [comment]
I've fixed this problem on my local computer.
I downloaded the official source code and fixed the problem.
AndResGuard-master/AndResGuard-gradle-plugin/src/main/groovy/com.tentcent.gradle/AndResGuardTask

line 53 : modify "variant.variantData.VariantConfiguration.signingConfig" to "variant.variantData.variantDslInfo.signingConfig"

line 54: modify "variant.variantData.VariantConfiguration.applicationId" to "variant.variantData.variantDslInfo.applicationId"

I strongly suggest changing the version number to distinguish it from the official version.

modify file gradle.properties 
ANDRESGUARD_VESSION=1.2.17.gradle4

And then Build,

You can find some jars in build/libs;

Or  you can pass under steps.

download lib.zip in this link.

unzip it to your project's root folder.

add Code like this:
buildscript {
[lib.zip](https://github.com/shwenzhang/AndResGuard/files/4700154/lib.zip)
    repositories {
       // ................................................
        maven { url "$rootDir/lib/" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
       // ....................................................................................
        classpath("com.google.gradle:osdetector-gradle-plugin:1.6.2")
        classpath("com.tencent.mm:AndResGuard-core:1.2.17")
        classpath("com.tencent.mm:AndResGuard-gradle-plugin:1.2.17.gradle4") { changing = true }
    }
}

And you will build succeed.

Good luck!

**Comment by yuhlzu** [comment]
> https://stackoverflow.com/questions/62075122/no-such-property-variantconfiguration-for-class
> In the last gradle Relase ApplicationVariant implement BaseVariant
> 
> Instead of
> 
> def buildType = variant.variantData.variantConfiguration.buildType.name
> Should be
> 
> def buildType = variant.buildType.name
> 
> 希望该项目有人继续尽快跟进啊

Same Problem.
顶

**Comment by PavelDolbik** [comment]
If you are using `com.google.firebase:firebase-crashlytics-gradle` dependency in your project, just update to version `2.0.0-beta04` it is helped to me.

**Comment by HoustonMuzamhindo** [comment]
> If you are using `com.google.firebase:firebase-crashlytics-gradle` dependency in your project, just update to version `2.0.0-beta04` it is helped to me.

This worked for me. I just updated the crashlytics dependency version using the one Android Studio was suggesting and it worked.
