### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by leleliu008** [shwenzhang/AndResGuard#421]
[Configuration.java#L325](https://github.com/shwenzhang/AndResGuard/blob/master/AndResGuard-core/src/main/java/com/tencent/mm/resourceproguard/Configuration.java#L325) 

从`config.xml`中读取出来的`keystore`文件路径，如果是相对路径，应该相关对于`config.xml`文件的路径更好。因为这个值一般不会写死成绝对路径。

```
java -jar AndResGuard-cli-1.2.16.jar \
    ~/Android-DateTime-for-the-aged/Android-DateTime-for-the-aged_1.0.0_20200316_211418_debug.apk \
    -config ~/Android-DateTime-for-the-aged/AndResGuard-config.xml \
    -7zip /usr/local/bin/7za \
    -zipalign /usr/local/opt/android-sdk/build-tools/28.0.3/zipalign \
    -signatureType v2 \
    -out ~/xx/yy
```

```
java.io.IOException: the signature file do not exit, raw path= /usr/local/share/zsh/site-functions/./keystore.jks

	at com.tencent.mm.resourceproguard.Configuration.readSignFromXml(Configuration.java:325)
	at com.tencent.mm.resourceproguard.Configuration.readXmlConfig(Configuration.java:221)
	at com.tencent.mm.resourceproguard.Configuration.<init>(Configuration.java:107)
	at com.tencent.mm.resourceproguard.cli.CliMain.loadConfigFromXml(CliMain.java:268)
	at com.tencent.mm.resourceproguard.cli.CliMain.run(CliMain.java:224)
	at com.tencent.mm.resourceproguard.cli.CliMain.main(CliMain.java:38)
```

**Comment by simpleton** [comment]
欢迎PR :)

**Comment by leleliu008** [comment]
@simpleton  我发起了一个`PR`

**Comment by i-show** [comment]
-signatureType v2 
使用V2  签名方法标记一下
