### ISSUE TITLE
这是什么问题？

### ISSUE THREAD

**Issue by amyliu1062** [shwenzhang/AndResGuard#44]
在运行gradle中andresguard/generate时
报了下面这两个错误：

an not find the compress dataresFile=res/anim/slide_top_out.xml
can not find res file, you delete it? path: resFile=/Users/liudan/work/xx/build/outputs/apk/AndResProguard/temp/res/anim/slide_top_out.xml
can not find the compress dataresFile=res/anim/xr_slide_in_top.xml
can not find res file, you delete it? path: resFile=/Users/liudan/work/xx/build/outputs/apk/AndResProguard/temp/res/anim/xr_slide_in_top.xml
can not find the compress dataresFile=res/anim/xr_slide_out_bottom.xml
can not find res file, you delete it? path: resFile=/Users/liudan/work/xx/build/outputs/apk/AndResProguard/temp/res/anim/xr_slide_out_bottom.xml
以上资源在项目中有

java.io.IOException: Cannot run program "/Users/liudan/work/file/zip": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.tencent.mm.androlib.ResourceApkBuilder.alignApk(ResourceApkBuilder.java:154)
	at com.tencent.mm.androlib.ResourceApkBuilder.alignApk(ResourceApkBuilder.java:138)
	at com.tencent.mm.androlib.ResourceApkBuilder.buildApk(ResourceApkBuilder.java:48)
这个是zipAlignPath和sevenZipPath，文件权限我都设置成everyone可读可写了。

不知道是什么问题，可以指点一下吗？

**Comment by simpleton** [comment]
duplicate #45
