### ISSUE TITLE
给apk设置特定的packageId之后，资源混淆失败

### ISSUE THREAD

**Issue by Fredlxy** [shwenzhang/AndResGuard#450]
插件化项目做资源共享，给插件工程设置了特定的packageId之后，资源混淆失败
android {
	aaptOptions {
        additionalParameters '--allow-reserved-package-id','--package-id','0x79'
    }
}
com.tencent.mm.androlib.AndrolibException: Could not decode arsc file
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.write(ARSCDecoder.java:130)
	at com.tencent.mm.androlib.ApkDecoder.decode(ApkDecoder.java:197)
	at com.tencent.mm.resourceproguard.Main.decodeResource(Main.java:114)
	at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:98)
	at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:84)
	at com.tencent.mm.resourceproguard.cli.CliMain.run(CliMain.java:243)
	at com.tencent.mm.resourceproguard.cli.CliMain.main(CliMain.java:38)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at com.mindprod.ledatastream.LEDataInputStream.readFully(LEDataInputStream.java:180)
	at com.tencent.mm.util.DataInputDelegate.readFully(DataInputDelegate.java:67)
	at com.tencent.mm.util.ExtDataOutput.writeBytes(ExtDataOutput.java:22)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.reWriteTable(ARSCDecoder.java:325)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.writeTable(ARSCDecoder.java:235)
	at com.tencent.mm.androlib.res.decoder.ARSCDecoder.write(ARSCDecoder.java:128)
	... 6 more

**Comment by HsXuTao** [comment]
遇到了同样的问题，希望能解决一下，谢谢

**Comment by mowenGithub** [comment]
遇到同样的问题+1

**Comment by soulresisdent** [comment]
遇到同样的问题

**Comment by diewu0421** [comment]
遇到同样的问题+1

**Comment by soulresisdent** [comment]
我已经搞定了。需要帮助不







在 2021-09-28 10:45:10，"diewu0421" ***@***.***> 写道：

遇到同样的问题+1

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mowenGithub** [comment]
@soulresisdent 请问怎么解决的

**Comment by linsir6** [comment]
@mowenGithub @MrWu94 @soulresisdent @HsXuTao 大家遇到类似问题的，可以试一下，https://github.com/shwenzhang/AndResGuard/pull/516 类似这样的修改～
