### ISSUE TITLE
com.tencent.mm.androlib.AndrolibException: can not find \ or raw string in res path = Time

### ISSUE THREAD

**Issue by lihong199705** [shwenzhang/AndResGuard#474]
版本号   AndResGuard-gradle-plugin:1.2.20
gradlew resguardRelease时出现问题，callstack见最下方
而gradlew resguardDebug不会有问题

同时，使用tool_output 下的AndResGuard-cli-1.2.15.jar包，java -jar .\AndResGuard-cli-1.2.15.jar .\test.apk -config .\config.xml指定release版本的apk时，也是同样的问题

callstack如下，具体同https://github.com/shwenzhang/AndResGuard/issues/196相似
com.tencent.mm.androlib.AndrolibException: can not find \ or raw string in res path = Time
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:666)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:524)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:476)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:418)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:302)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:195)
        at com.tencent.mm.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:111)
        at com.tencent.mm.androlib.ApkDecoder.decode(ApkDecoder.java:182)
        at com.tencent.mm.resourceproguard.Main.decodeResource(Main.java:113)
        at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:97)
        at com.tencent.mm.resourceproguard.Main.resourceProguard(Main.java:83)
        at com.tencent.mm.resourceproguard.cli.CliMain.run(CliMain.java:243)
        at com.tencent.mm.resourceproguard.cli.CliMain.main(CliMain.java:38)

**Comment by m733338844** [comment]
怎么解决呢

**Comment by LuckyLi97** [comment]
> 怎么解决呢
对比了下，使用dexguard后，resources.arsc的文件在解析时已经变得不一样了，可能真的不能混用吧
