### ISSUE TITLE
使用/tool_output/文件夹下的工具混淆资源后Mob短信验证报错

### ISSUE THREAD

**Issue by ruidalin** [shwenzhang/AndResGuard#60]
Mob网址  http://www.mob.com/ 
使用的jar包和aar文件

不知道什么原因 , 求帮忙

config.xml 的白名单我不使用 
<issue id="whitelist" isactive="false">

报错如下
E/art: dlopen("/data/data/com.yzrm.mm/files/libsmssdk.so.22", RTLD_LAZY) failed: dlopen failed: library "/data/data/com.yzrm.mm/files/libsmssdk.so.22" not found

E/art: No implementation found for void cn.smssdk.utils.SPHelper.nativeInit(android.content.Context) (tried Java_cn_smssdk_utils_SPHelper_nativeInit and Java_cn_smssdk_utils_SPHelper_nativeInit__Landroid_content_Context_2)

A/MobUncaughtExceptionHandler: No implementation found for void cn.smssdk.utils.SPHelper.nativeInit(android.content.Context) (tried Java_cn_smssdk_utils_SPHelper_nativeInit and Java_cn_smssdk_utils_SPHelper_nativeInit__Landroid_content_Context_2)
                               java.lang.UnsatisfiedLinkError: No implementation found for void cn.smssdk.utils.SPHelper.nativeInit(android.content.Context) (tried Java_cn_smssdk_utils_SPHelper_nativeInit and Java_cn_smssdk_utils_SPHelper_nativeInit__Landroid_content_Context_2)
                                   at cn.smssdk.utils.SPHelper.nativeInit(Native Method)
                                   at cn.smssdk.utils.SPHelper.<init>(Unknown Source)
                                   at cn.smssdk.utils.SPHelper.getInstance(Unknown Source)
                                   at cn.smssdk.net.e.<init>(Unknown Source)
                                   at cn.smssdk.net.e.a(Unknown Source)
                                   at cn.smssdk.a.<init>(Unknown Source)
                                   at cn.smssdk.SMSSDK.initSDK(Unknown Source)
                                   at cn.smssdk.SMSSDK.initSDK(Unknown Source)
                                   at com.yzrm.mm.activity.RlResetPasswdActivity.onCreate(Unknown Source)
                                   at android.app.Activity.performCreate(Activity.java:5977)
                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2415)
                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
                                   at android.app.ActivityThread.access$800(ActivityThread.java:167)
                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419)
                                   at android.os.Handler.dispatchMessage(Handler.java:111)
                                   at android.os.Looper.loop(Looper.java:194)
                                   at android.app.ActivityThread.main(ActivityThread.java:5546)
                                   at java.lang.reflect.Method.invoke(Native Method)
                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by simpleton** [comment]
能否把使用压缩前，和使用压缩后的apk发送到我的邮箱呢？ 我来分析一下原因。
sunsj1231@gmail.com

**Comment by ruidalin** [comment]
@simpleton 
在此对你的帮助表示感谢

该问题我已经解决
看日志的关键
library "/data/data/com.yzrm.mm/files/libsmssdk.so.22" not found
用adb shell 进入到该目录下查看确实是没有该文件生成 . 安装没有混淆之前的apk , 在该目录下就会生成libsmssdk.so.22文件 . 问题大概是混淆后有文件不能被正确加载了, 到Mob的官网下载最新的短信SDK v2.0.2( http://www.mob.com/download/sms/android?p=studio ) 发现除了jar包之外就只有aar文件 , 并没有so文件 , 把SMSSDK-2.0.2.aar修改后缀名为.zip ,解压出来 , 鉴于是资源文件的混淆 , 找到/res/raw/libs 文件用记事本打开(有部分乱码)查找关键字libsmssdk 发现能找到libsmssdk.so 的关键字 , 只要保证libs 文件不混淆就能生成libsmssdk.so.22 文件
修改混淆工具的config.xml
< issue id="whitelist" isactive="**true**">
         
         < path value="**com.yzrm.mm.R.raw.libs**"/>
< /issue>

混淆之后就不会报错了

**Comment by simpleton** [comment]
@ruidalin 多谢你的方案，我会把这个坑加入QA中。也环境PR
