### ISSUE TITLE
请帮忙看一下 无法签名的原因

### ISSUE THREAD

**Issue by michaellct** [shwenzhang/AndResGuard#7]
谢谢提供这么好的工具 现在遇到一个问题，请帮忙看下是不是我这边配置的问题 谢谢！
e:\work>java -jar resourcesproguard.jar input.apk
resourceprpguard begin
reading config file, e:\work\config.xml
mKeepRoot false
unziping apk to e:\work\input\temp
decoding resources.arsc
parse to get the exist names in the resouces.arsc first
reading packagename jp.wasabeef.example.recyclerview
resources mapping file e:\work\input\resource_mapping_input.txt done
writing new resources.arsc
resources.arsc Character Encoding: utf-8
resources.arsc reduece: 39.949219kb, time cost from begin: 1.052000s
general unsigned apk: input_unsigned.apk
general unsigned apk input_unsigned.apk done, file reduce: 200.967773kb, time co
st from begin: 1.422000s
signing apk: input_signed.apk
java.io.IOException: Cannot run program "jarsigner": CreateProcess error=2, 系统
找不到指定的文件。
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at com.tencent.mm.androlib.ResourceApkBuilder.signApk(ResourceApkBuilder
.java:135)
        at com.tencent.mm.androlib.ResourceApkBuilder.buildApk(ResourceApkBuilde
r.java:46)
        at com.tencent.mm.resourceproguard.Main.run(Main.java:326)
        at com.tencent.mm.resourceproguard.Main.main(Main.java:67)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 8 more

**Comment by shwenzhang** [comment]
@michaellct ,java.io.IOException: Cannot run program "jarsigner": CreateProcess error=2, 系统
找不到指定的文件。是否安装了jdk,并且放到环境变量

**Comment by michaellct** [comment]
@shwenzhang 谢谢 配置jdk到环境变量后 可以正确打包签名apk了
