### ISSUE TITLE
Looks like not support LambdaExpression

### ISSUE THREAD

**Issue by ityancs** [shwenzhang/AndResGuard#87]
java.lang.UnsupportedOperationException: Unknown ASTNode child: LambdaExpression

**Comment by simpleton** [comment]
Could you provide more detail logs for helping me debug this issue?

**Comment by ityancs** [comment]
Sure,my pleasure~ 
Maybe because I used the 
    me.tatarka:gradle-retrolambda:3.2.5.

Failed converting ECJ parse tree to Lombok for file /my/file.java
java.lang.UnsupportedOperationException: Unknown ASTNode child: LambdaExpression
	at lombok.ast.ecj.EcjTreeVisitor.visitOther(EcjTreeVisitor.java:368)
	at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:364)
	at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
	at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:236)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:282)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:252)
	at lombok.ast.ecj.EcjTreeConverter.access$100(EcjTreeConverter.java:141)
	at lombok.ast.ecj.EcjTreeConverter$2.visitMessageSend(EcjTreeConverter.java:1042)
	at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:156)
	at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
	at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:236)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:282)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:252)
	at lombok.ast.ecj.EcjTreeConverter.toBlock(EcjTreeConverter.java:397)
	at lombok.ast.ecj.EcjTreeConverter.access$1500(EcjTreeConverter.java:141)
	at lombok.ast.ecj.EcjTreeConverter$2.visitMethodDeclaration(EcjTreeConverter.java:1241)
	at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:152)
	at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
	at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:236)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:282)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:252)
	at lombok.ast.ecj.EcjTreeConverter.access$100(EcjTreeConverter.java:141)
	at lombok.ast.ecj.EcjTreeConverter$2.createNormalTypeBody(EcjTreeConverter.java:563)
	at lombok.ast.ecj.EcjTreeConverter$2.visitTypeDeclaration(EcjTreeConverter.java:486)
	at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:48)
	at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
	at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:236)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:282)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:252)
	at lombok.ast.ecj.EcjTreeConverter.access$100(EcjTreeConverter.java:141)
	at lombok.ast.ecj.EcjTreeConverter$2.visitCompilationUnitDeclaration(EcjTreeConverter.java:441)
	at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:264)
	at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
	at com.android.tools.lint.EcjParser.parseJava(EcjParser.java:511)
	at com.android.tools.lint.client.api.JavaVisitor.visitFile(JavaVisitor.java:247)
	at com.android.tools.lint.client.api.LintDriver.checkJava(LintDriver.java:1529)
	at com.android.tools.lint.client.api.LintDriver.runFileDetectors(LintDriver.java:1063)
	at com.android.tools.lint.client.api.LintDriver.checkProject(LintDriver.java:908)
	at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.java:436)
	at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.java:377)
	at com.android.tools.lint.LintCliClient.run(LintCliClient.java:131)
	at com.android.build.gradle.internal.LintGradleClient.run(LintGradleClient.java:133)
	at com.android.build.gradle.internal.LintGradleClient$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.android.build.gradle.tasks.Lint.runLint(Lint.groovy:223)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at com.android.build.gradle.tasks.Lint.lintSingleVariant(Lint.groovy:198)
	at com.android.build.gradle.tasks.Lint$lintSingleVariant$2.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at com.android.build.gradle.tasks.Lint.lint(Lint.groovy:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

But I can build success and the apk runs great. I wonder the error if make some effect!

**Comment by simpleton** [comment]
This warning is caused by android-lint, currently lint didn't support lambda expression.

**Comment by ityancs** [comment]
Thank you very much~~
