### ISSUE TITLE
file count问题

### ISSUE THREAD

**Issue by TracyZhangLei** [shwenzhang/AndResGuard#89]
the file count of AAA , and the file count of BBB is not equal, there must be some problem, please contact shwenzhang for detail

	at com.tencent.mm.androlib.ResourceApkBuilder.generalUnsignApk(ResourceApkBuilder.java:248)
	at com.tencent.mm.androlib.ResourceApkBuilder.buildApk(ResourceApkBuilder.java:45)
	at com.tencent.mm.resourceproguard.Main.run(Main.java:326)
	at com.tencent.mm.resourceproguard.Main.main(Main.java:67)

**Comment by simpleton** [comment]
可以先尝试一下clean下，如果还是必现的话。麻烦发一份apk到 `sunsj1231@gmail.com` 吧

**Comment by TracyZhangLei** [comment]
@simpleton 你好，jar包从1.0版本升级到1.1.9可以么？除了CliMain之外，有什么要调整么？

**Comment by simpleton** [comment]
jar的project的gradle应该有任务来生成，你可以在`tool_output`目录下找到最新的jar包。

**Comment by TracyZhangLei** [comment]
使用1.1.9已经可以了．
